<?php
$csvData = <<<EOD
1;LH.01.01;LANDED HOUSE-01;SUNARTO URJOYO PURBA;EMPLOYEE BADGE;20047;EMPLOYEE;HSE MANAGER;SR. STAFF - MANAGER;HSE;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;OFFICE U SMELTER CANTEEN;SATELIT CANTEEN;;;;;RESIDENCE CARD (NIK);EMPLOYEE;BOD;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;
2;LH.01.02;LANDED HOUSE-01;CHRISTIAN BAMBANG KHRISNA MUKTI;EMPLOYEE BADGE;20055;EMPLOYEE;FURNACE MANAGER;SR. STAFF - MANAGER;PP - FURNACE;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;OFFICE U SMELTER CANTEEN;SATELIT CANTEEN;;;;;DRIVING LICENSE;EXECUTIVE;SR. STAFF;SPECIAL GUEST;ROOM DELIVERY;ENFI CANTEEN;
3;LH.02.01;LANDED HOUSE-02;MR. ZHENG BU DONG;EMPLOYEE BADGE;30001;CONSULTANT;ENFI DIRECTOR;BOD;ENFI;ENFI;SPECIAL GUEST;STANDARD BUFFET;ENFI CANTEEN;ENFI CANTEEN;ENFI CANTEEN;;;;;EMPLOYEE BADGE;GOVERNMENT OFFICER;SR. STAFF - GM & EQUIVALENT;EXECUTIVE/ VIPs GUEST;VIP BUFFET;EXPAT CANTEEN;
4;LH.03.01;LANDED HOUSE-03;TA'DUNG;EMPLOYEE BADGE;A1071;EMPLOYEE;OPERATIONAL SMELTER SPECIALIST;SR. STAFF - ENGINEER/ SPECIALIST;OPERATION READINESS SMELTER RKEF;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;PASSPORT;CONSULTANT;SR. STAFF - MANAGER;;;EXPLORATION MESS CANTEEN;
5;LH.03.02;LANDED HOUSE-03;REINHARD SIAHAAN;EMPLOYEE BADGE;20658;EMPLOYEE;EMU GENERAL MANAGER;SR. STAFF - GM & EQUIVALENT;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;CONTRACTOR;SR. STAFF - ENGINEER/ SPECIALIST;;;LIVING 3 CANTEEN;
6;LH.04.01;LANDED HOUSE-04;SUWARTO PRAWIROATMODJO;EMPLOYEE BADGE;11108;EMPLOYEE;ADVISOR;SR. STAFF;ADVISOR;PT. CNI;SPECIAL GUEST;ROOM DELIVERY;STAY MESS;OFFICE U SMELTER CANTEEN;STAY MESS;;;;;;OTHERS;SR. STAFF - SUPERINTENDENT;;;MINING CANTEEN;
7;LH.04.02;LANDED HOUSE-04;ANDRE CH MR DAENUWY;EMPLOYEE BADGE;11110;EMPLOYEE;ADVISOR;SR. STAFF;ADVISOR;PT. CNI;SPECIAL GUEST;ROOM DELIVERY;STAY MESS;OFFICE U SMELTER CANTEEN;STAY MESS;;;;;;;STAFF;;;OFFICE U SMELTER CANTEEN;
8;LH.05.01;LANDED HOUSE-05;SLAMET SURYANTO;EMPLOYEE BADGE;A1061;EMPLOYEE;ENGINEERING MAINTENANCE & UTILITIES SPECIALIST;SR. STAFF - ENGINEER/ SPECIALIST;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;OFFICE U SMELTER CANTEEN;SATELIT CANTEEN;;;;;;;STAFF - SUPERVISOR;;;SAMAENRE CANTEEN;
9;LH.05.02;LANDED HOUSE-05;SYAMSI BUANG;EMPLOYEE BADGE;20035;EMPLOYEE;PROCESS OPERATION GENERAL MANAGER ;SR. STAFF - GM & EQUIVALENT;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;OFFICE U SMELTER CANTEEN;SATELIT CANTEEN;;;;;;;STAFF - ENGINEER/ GEOLOGIST;;;SATELIT CANTEEN;
10;LH.06.01;LANDED HOUSE-06;ROIMON BARUS;EMPLOYEE BADGE;20780;EXECUTIVE;PT. CMP SMELTER DIRECTOR;BOD;PP;PT. CNI;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;OFFICE U SMELTER CANTEEN;SATELIT CANTEEN;;;;;;;STAFF - OFFICER;;;STAY MESS;
11;LH.06.02;LANDED HOUSE-06;YARIS TANDI ;EMPLOYEE BADGE;A1012;EMPLOYEE;ADVISOR;SR. STAFF;ADVISOR;PT. CNI;SPECIAL GUEST;STANDARD BUFFET;SATELIT CANTEEN;OFFICE U SMELTER CANTEEN;SATELIT CANTEEN;;;;;;;NON STAFF;;;VIP A1 VENUE;
12;LH-07.01;LANDED HOUSE-07;ALIMUDDIN TOLA;EMPLOYEE BADGE;20022;EMPLOYEE;DRYER MANAGER;SR. STAFF - MANAGER;PP - DRYER;PT. CNI;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;OFFICE U SMELTER CANTEEN;SATELIT CANTEEN;;;;;;;NON STAFF - OPERATOR;;;VIP A2 VENUE;
13;LH-07.02;LANDED HOUSE-07;BUSYAIRI;EMPLOYEE BADGE;20657;EMPLOYEE;PROCESS PLANT MAINTENANCE MANAGER;SR. STAFF - MANAGER;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;OFFICE U SMELTER CANTEEN;SATELIT CANTEEN;;;;;;;;;;WOLO CANTEEN;
14;LH.08.01;LANDED HOUSE-08;IMRAN ROSJADI PABITJARA;EMPLOYEE BADGE;A1068;EMPLOYEE;OR SR. SPECIALIST;SR. STAFF - ENGINEER/ SPECIALIST;OPERATION READINESS SMELTER RKEF;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;OFFICE U SMELTER CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
15;LH.08.02;LANDED HOUSE-08;AGUSTINUS LONTOH;EMPLOYEE BADGE;C.128;EMPLOYEE;OR SR. SPECIALIST;SR. STAFF - ENGINEER/ SPECIALIST;OPERATION READINESS SMELTER RKEF;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;OFFICE U SMELTER CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
16;LH.09.01;LANDED HOUSE-09;ANDI MAPPASELA;EMPLOYEE BADGE;A1010;EMPLOYEE;GENERAL FACILITIES SERFICES GENERAL MANAGER;SR. STAFF - GM & EQUIVALENT;GFS;PT. CNI;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;OFFICE U SMELTER CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
17;LH.09.02;LANDED HOUSE-09;LUSYAN TADUNG;EMPLOYEE BADGE;20681;EMPLOYEE;MANAGER UTILITIES;SR. STAFF - MANAGER;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;OFFICE U SMELTER CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
18;LH.10.01;LANDED HOUSE-10;ALFINA WIJANARNO;EMPLOYEE BADGE;20398;EMPLOYEE;EMU MANAGER;SR. STAFF - MANAGER;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;OFFICE U SMELTER CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
19;LH.10.02;LANDED HOUSE-10;ALIM SIDDIQ SOLEH;EMPLOYEE BADGE;20084;EMPLOYEE;REDUCTION KILN MANAGER;SR. STAFF - MANAGER;PP - KILN;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;OFFICE U SMELTER CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
20;DM.A2.101;DORMITORY A2;HERMANSYAH MARZUKI;EMPLOYEE BADGE;20806;EMPLOYEE;[CMP] SITE GENERAL AFFAIR MANAGER;SR. STAFF - MANAGER;SITE GENERAL AFFAIR;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
21;DM.A2.102;DORMITORY A2;GELORA F. GINTING;EMPLOYEE BADGE;20043;EMPLOYEE;[CMP] SUPPLY CHAIN MANAGEMENT MANAGER;SR. STAFF - MANAGER;SCM;PT. CMP;SPECIAL GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
22;DM.A2.103;DORMITORY A2;BADDU M;EMPLOYEE BADGE;20353;EMPLOYEE;[D] SHIFT DRYER & TRANSPORTATION SUPERINTENDENT;SR. STAFF - SUPERINTENDENT;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
23;DM.A2.104;DORMITORY A2;YUSTISIA PANDU MAHENDRATA;EMPLOYEE BADGE;20109;EMPLOYEE;HUMAN CAPITAL BUSINESS PARTNER & INDUSTRIAL RELATION SUPERINTENDENT;SR. STAFF - SUPERINTENDENT;HC;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
24;DM.A2.105;DORMITORY A2;SRI WAHONO;EMPLOYEE BADGE;20359;EMPLOYEE;[C] SHIFT REDUCTION KILN SUPERINTENDENT;SR. STAFF - SUPERINTENDENT;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
25;DM.A2.106;DORMITORY A2;SAIFULLAH;EMPLOYEE BADGE;10830;EMPLOYEE;TRANSPORTATION & TRAVEL SUPERINTENDENT;SR. STAFF - SUPERINTENDENT;SITE GENERAL AFFAIR;PT. CNI;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
26;DM.A2.106;DORMITORY A2;ANDI KEMAL;EMPLOYEE BADGE;11409;EMPLOYEE;LANDSCAPE, GARDENING, & CLEANING SERVICES COORDINATOR & TEAM;STAFF - SUPERVISOR;SITE GENERAL AFFAIR;PT. CNI;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
27;DM.A2.107;DORMITORY A2;ADI NUGROHO;EMPLOYEE BADGE;20777;EMPLOYEE;PROCESS DEVELOPMENT SUPERINTENDENT;SR. STAFF - SUPERINTENDENT;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
28;DM.A2.108;DORMITORY A2;FRANSCICHUS VERI;;;;LABORATORY SPECIALIST;SR. STAFF - ENGINEER/ SPECIALIST;SCM;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
29;DM.A2.109;DORMITORY A2;YANDERSON ALAMAKO;EMPLOYEE BADGE;20088;EMPLOYEE;LOGISTIC & MATERIAL HANDLING SERVICES SUPERINTENDENT;SR. STAFF - SUPERINTENDENT;SCM;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
30;DM.A2.110;DORMITORY A2;HERBANU ADHI;EMPLOYEE BADGE;20098;EMPLOYEE;WAREHOUSING & INVENTORY MANAGEMENT SUPERINTENDENT;SR. STAFF - SUPERINTENDENT;SCM;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
31;DM.A2.111;DORMITORY A2;MANGARA TUA SIDABUTAR;EMPLOYEE BADGE;20749;EMPLOYEE;HUMAN CAPITAL MANAGER;SR. STAFF - MANAGER;HC;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
32;DM.A2.112;DORMITORY A2;THOMAS TONGLOKARUA;EMPLOYEE BADGE;20349;EMPLOYEE;[D] SHIFT REDUCTION KILN SUPERINTENDENT;SR. STAFF - SUPERINTENDENT;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
33;DM.A2.113;DORMITORY A2;KUNCORO NURYANTO;EMPLOYEE BADGE;20344;EMPLOYEE;AUTOMATION ENGINEER;SR. STAFF - ENGINEER/ SPECIALIST;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
34;DM.A2.114;DORMITORY A2;MUJAHID LAOLA;EMPLOYEE BADGE;20325;EMPLOYEE;[D] SHIFT FURNACE SUPERINTENDENT;SR. STAFF - SUPERINTENDENT;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
35;DM.A2.115;DORMITORY A2;AHMAD JULIAN PUTRA;EMPLOYEE BADGE;20111;EMPLOYEE;[CMP] ELECTRICAL ENGINEER;SR. STAFF - ENGINEER/ SPECIALIST;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
36;DM.A2.116;DORMITORY A2;BAKRI HARISI;EMPLOYEE BADGE;20338;EMPLOYEE;[B] SHIFT REDUCTION KILN SUPERINTENDENT;SR. STAFF - SUPERINTENDENT;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
37;DM.A2.117;DORMITORY A2;AR ALAM WILSON SILIWANGI;EMPLOYEE BADGE;20094;EMPLOYEE;ELECTRICAL SENIOR ENGINEER;SR. STAFF - ENGINEER/ SPECIALIST;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
38;DM.A2.118;DORMITORY A2;RASAK;EMPLOYEE BADGE;20351;EMPLOYEE;[B] SHIFT DRYER & TRANSPORTATION SUPERINTENDENT;SR. STAFF - SUPERINTENDENT;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
39;DM.A2.119;DORMITORY A2;HENDRIK ALBERT SCHWEIDZER TIMISELA;EMPLOYEE BADGE;20478;EMPLOYEE;MAINTENANCE UTILITIES SUPERINTENDENT;SR. STAFF - SUPERINTENDENT;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
40;DM.A2.120;DORMITORY A2;PIHERIN RASYID;EMPLOYEE BADGE;20352;EMPLOYEE;[C] SHIFT DRYER & TRANSPORTATION SUPERINTENDENT;SR. STAFF - SUPERINTENDENT;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
41;DM.A2.201;DORMITORY A2;JONATHAN TAMBUNAN;EMPLOYEE BADGE;20632;EMPLOYEE;PROCESS TECHNOLOGY MANAGER;SR. STAFF - MANAGER;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
42;DM.A2.202;DORMITORY A2;BERNADUS BENY;EMPLOYEE BADGE;20112;EMPLOYEE;ENGINEERING & RELIABILITY SUPERINTENDENT;SR. STAFF - SUPERINTENDENT;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
43;DM.A2.203;DORMITORY A2;SARLIN;EMPLOYEE BADGE;11626;EMPLOYEE;DOMESTIC WASTE MANAGEMENT SUPERINTENDENT;SR. STAFF - SUPERINTENDENT;SITE GENERAL AFFAIR;PT. CNI;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
44;DM.A2.204;DORMITORY A2;MUSALANGI;EMPLOYEE BADGE;20108;EMPLOYEE;STEADY DAY COAL MILL SUPERINTENDENT;SR. STAFF - SUPERINTENDENT;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
45;DM.A2.205;DORMITORY A2;BUTRO;EMPLOYEE BADGE;20110;EMPLOYEE;MAINTENANCE SHIFT SUPERINTENDENT;SR. STAFF - SUPERINTENDENT;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
46;DM.A2.206;DORMITORY A2;ABU BAKAR KABALMAY;EMPLOYEE BADGE;20048;EMPLOYEE;DRYER & TRANSPORTATION STEADY DAY SUPERINTENDENT;SR. STAFF - SUPERINTENDENT;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
47;DM.A2.207;DORMITORY A2;ILHAM;EMPLOYEE BADGE;20114;EMPLOYEE;FURNACE MAINTENANCE SUPERINTENDENT;SR. STAFF - SUPERINTENDENT;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
48;DM.A2.208;DORMITORY A2;DADANG CHAERUDDIN;EMPLOYEE BADGE;20050;EMPLOYEE;STEADY DAY FURNACE SUPERINTENDENT;SR. STAFF - SUPERINTENDENT;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
49;DM.A2.209;DORMITORY A2;DECKY SULLE;EMPLOYEE BADGE;20200;EMPLOYEE;FABRICATION SHOP SUPERINTENDENT;SR. STAFF - SUPERINTENDENT;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
50;DM.A2.210;DORMITORY A2;MUSRAM MA'RUF;EMPLOYEE BADGE;20191;EMPLOYEE;REDUCTION KILN STEADY DAY SUPERINTENDENT;SR. STAFF - SUPERINTENDENT;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
51;DM.A2.211;DORMITORY A2;ASRUL SANI PONGSIMPIN;EMPLOYEE BADGE;20106;EMPLOYEE;INSTRUMENT SPECIALIST & QC INSTRUMENT;SR. STAFF - ENGINEER/ SPECIALIST;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
52;DM.A2.212;DORMITORY A2;ADI SAMPE NURTOLU;EMPLOYEE BADGE;20206;EMPLOYEE;[A] SHIFT REDUCTION KILN SUPERINTENDENT;SR. STAFF - SUPERINTENDENT;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
53;DM.A2.213;DORMITORY A2;SEMUEL SANDA TODING;EMPLOYEE BADGE;20181;EMPLOYEE;MAINTENANCE SPECIALIST;SR. STAFF - ENGINEER/ SPECIALIST;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
54;DM.A2.214;DORMITORY A2;VACANT;;;;;;;;;;;;;;;;;;;;;;;
55;DM.A2.215;DORMITORY A2;NOBER SIALLO;EMPLOYEE BADGE;20021;EMPLOYEE;DRYER & KILN MAINTENANCE SUPERINTENDENT;SR. STAFF - SUPERINTENDENT;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
56;DM.A2.216;DORMITORY A2;FREDDY ROBBY ROMPAS;EMPLOYEE BADGE;20208;EMPLOYEE;[A] SHIFT DRYER & TRANSPORTATION SUPERINTENDENT;SR. STAFF - SUPERINTENDENT;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
57;DM.A2.217;DORMITORY A2;AGUSTINUS MATONGAN;EMPLOYEE BADGE;20205;EMPLOYEE;UTILITIES OPERATION SUPERINTENDENT;SR. STAFF - SUPERINTENDENT;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
58;DM.A2.218;DORMITORY A2;ASDAR NURDIN;EMPLOYEE BADGE;20270;EMPLOYEE;[B] SHIFT FURNACE SUPERINTENDENT;SR. STAFF - SUPERINTENDENT;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
59;DM.A2.219;DORMITORY A2;SELESTINUS ICHSAN PRATAMA EWANG;EMPLOYEE BADGE;20334;EMPLOYEE;[ER] CIVIL ENGINEER;SR. STAFF - ENGINEER/ SPECIALIST;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
60;DM.A2.220;DORMITORY A2;MUSTAFA;EMPLOYEE BADGE;20688;EMPLOYEE;[C] SHIFT FURNACE SUPERINTENDENT;SR. STAFF - SUPERINTENDENT;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
61;DM.A3.101;DORMITORY A3;PEBRIYADI;EMPLOYEE BADGE;20101;EMPLOYEE;SAFETY SUPERVISOR;STAFF - SUPERVISOR;HSE;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
62;DM.A3.101;DORMITORY A3;MARIHOT TUA MARBUN;EMPLOYEE BADGE;20751;EMPLOYEE;FIRE SUPERVISOR;STAFF - SUPERVISOR;HSE;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
63;DM.A3.102;DORMITORY A3;BRAM RYAN L. TOBING;EMPLOYEE BADGE;20278;EMPLOYEE;[CMP] PARAMEDIC;STAFF - OFFICER;HSE;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
64;DM.A3.102;DORMITORY A3;HAERUDDIN;EMPLOYEE BADGE;20049;EMPLOYEE;[A] SHIFT FURNACE SUPERVISOR;STAFF - SUPERVISOR;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
65;DM.A3.103;DORMITORY A3;MARTHEN RAPPE;EMPLOYEE BADGE;20190;EMPLOYEE;CONTAINER & BREAKBULK HANDLING SERVICES SUPERVISOR;STAFF - SUPERVISOR;SCM;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
66;DM.A3.103;DORMITORY A3;BILL MARNEO PONGTULURAN;EMPLOYEE BADGE;20090;EMPLOYEE;[DT] PROCESS ENGINEER SHIFT;STAFF - ENGINEER/ GEOLOGIST;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
67;DM.A3.104;DORMITORY A3;HERMAN YUDIONO;EMPLOYEE BADGE;20100;EMPLOYEE;[A] SHIFT LABORATORY & SAMPLE PREPARATION SUPERVISOR;STAFF - SUPERVISOR;PROD;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
68;DM.A3.104;DORMITORY A3;MOH. RISDIANTO;EMPLOYEE BADGE;20172;EMPLOYEE;[B] SHIFT LABORATORY & SAMPLE PREPARATION SUPERVISOR;STAFF - SUPERVISOR;PROD;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
69;DM.A3.105;DORMITORY A3;JOSEF JORY MALEKE;EMPLOYEE BADGE;20066;EMPLOYEE;[FM] PLANNER ELECTRICAL OR INSTRUMENT;STAFF - OFFICER;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
70;DM.A3.105;DORMITORY A3;LUMBAN SIANIPAR;EMPLOYEE BADGE;20365;EMPLOYEE;ELECTRICAL PROJECT SUPERVISOR;STAFF - SUPERVISOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
EOD;

$host = '127.0.0.1';
$db   = 'gfs_akomodasi';
$user = 'root';
$pass = '';

try {
     $pdo = new PDO("mysql:host=$host;dbname=$db;charset=utf8mb4", $user, $pass);
     $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

     $pdo->exec("SET FOREIGN_KEY_CHECKS = 0;");
     $pdo->exec("TRUNCATE TABLE guests");
     $pdo->exec("SET FOREIGN_KEY_CHECKS = 1;");

     // Fetch room map: room_no -> id
     $rooms = $pdo->query("SELECT id, room_no FROM rooms")->fetchAll(PDO::FETCH_ASSOC);
     $room_map = [];
     foreach ($rooms as $r) {
         $room_map[$r['room_no']] = $r['id'];
     }

     $lines = explode("\n", trim($csvData));
     $stmt = $pdo->prepare("INSERT INTO guests (room_id, name, personal_identification, reg_id_card, job, position, level_category, department, institution_company, occupants_category, meals_packages, breakfast_dp, lunch_dp, dinner_dp, registered_by, last_registration, remarks) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, NOW(), '')");

     $count = 0;
     foreach ($lines as $line) {
         $line = trim($line);
         if (empty($line)) continue;
         $cols = explode(";", $line);
         if (count($cols) < 16) continue;

         $room_no = trim($cols[1]);
         if (!isset($room_map[$room_no])) {
             continue; // Skip if room doesn't exist
         }

         $stmt->execute([
             $room_map[$room_no],
             trim($cols[3]), // name
             trim($cols[4]), // personal_identification
             trim($cols[5]), // reg_id_card
             trim($cols[6]), // job
             trim($cols[7]), // position
             trim($cols[8]), // level_category
             trim($cols[9]), // department
             trim($cols[10]), // institution_company
             trim($cols[11]), // occupants_category
             trim($cols[12]), // meals_packages
             trim($cols[13]), // breakfast_dp
             trim($cols[14]), // lunch_dp
             trim($cols[15]), // dinner_dp
             'Admin' // registered_by
         ]);
         $count++;
     }
     
     echo "Successfully inserted $count records into the guests table.\n";
     
} catch (\PDOException $e) {
     echo "Error: " . $e->getMessage() . "\n";
}
