<?php
$csvData = <<<EOD
401;DM.R2.214;DORMITORY R2;VACANT 1;;;;;;;;;;;;;;;;;;;;;;;
402;DM.R2.214;DORMITORY R2;VACANT 2;;;;;;;;;;;;;;;;;;;;;;;
403;DM.R2.214;DORMITORY R2;VACANT 3;;;;;;;;;;;;;;;;;;;;;;;
404;DM.R2.215;DORMITORY R2;VACANT 1;;;;;;;;;;;;;;;;;;;;;;;
405;DM.R2.215;DORMITORY R2;VACANT 2;;;;;;;;;;;;;;;;;;;;;;;
406;DM.R2.215;DORMITORY R2;VACANT 3;;;;;;;;;;;;;;;;;;;;;;;
407;DM.R2.216;DORMITORY R2;VACANT 1;;;;;;;;;;;;;;;;;;;;;;;
408;DM.R2.216;DORMITORY R2;VACANT 2;;;;;;;;;;;;;;;;;;;;;;;
409;DM.R2.216;DORMITORY R2;VACANT 3;;;;;;;;;;;;;;;;;;;;;;;
410;DM.R2.217;DORMITORY R2;VACANT 1;;;;;;;;;;;;;;;;;;;;;;;
411;DM.R2.217;DORMITORY R2;VACANT 2;;;;;;;;;;;;;;;;;;;;;;;
412;DM.R2.217;DORMITORY R2;VACANT 3;;;;;;;;;;;;;;;;;;;;;;;
413;DM.R2.218;DORMITORY R2;VACANT 1;;;;;;;;;;;;;;;;;;;;;;;
414;DM.R2.218;DORMITORY R2;VACANT 2;;;;;;;;;;;;;;;;;;;;;;;
415;DM.R2.218;DORMITORY R2;VACANT 3;;;;;;;;;;;;;;;;;;;;;;;
416;DM.R2.219;DORMITORY R2;VACANT 1;;;;;;;;;;;;;;;;;;;;;;;
417;DM.R2.219;DORMITORY R2;VACANT 2;;;;;;;;;;;;;;;;;;;;;;;
418;DM.R2.219;DORMITORY R2;VACANT 3;;;;;;;;;;;;;;;;;;;;;;;
419;DM.R2.220;DORMITORY R2;VACANT 1;;;;;;;;;;;;;;;;;;;;;;;
420;DM.R2.220;DORMITORY R2;VACANT 2;;;;;;;;;;;;;;;;;;;;;;;
421;DM.R2.220;DORMITORY R2;VACANT 3;;;;;;;;;;;;;;;;;;;;;;;
422;PF.B1.101;PREFAB B1;PIAN PATABANG;EMPLOYEE BADGE;20393;EMPLOYEE;[B] OPERATOR AIR COMPRESSOR (PLANT & INSTRUMENT AIR);NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
423;PF.B1.101;PREFAB B1;YANCE BARA PADANG;EMPLOYEE BADGE;20705;EMPLOYEE;[A] OPERATOR AIR COMPRESSOR (PLANT & INSTRUMENT AIR);NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
424;PF.B1.101;PREFAB B1;BINTARA ADI BUDI UTOMO;EMPLOYEE BADGE;20141;EMPLOYEE;[A] OPERATOR WATER CIRCULATING PUMP CHAMBER;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
425;PF.B1.102;PREFAB B1;MUH RELYM RAMLI;EMPLOYEE BADGE;20358;EMPLOYEE;[B] OPERATOR OXYGEN PLANT;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
426;PF.B1.102;PREFAB B1;ARNOLD SAPUTRA;EMPLOYEE BADGE;20140;EMPLOYEE;[A] OPERATOR OXYGEN PLANT;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
427;PF.B1.102;PREFAB B1;ERWIN;EMPLOYEE BADGE;10039;EMPLOYEE;LABORATORY OPERATION SUPERINTENDENT;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
428;PF.B1.103;PREFAB B1;SUNARDIANTO;EMPLOYEE BADGE;20143;EMPLOYEE;[A] OPERATOR WATER SUPPLY & DRAINAGE SHIFT;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
429;PF.B1.103;PREFAB B1;HERMIN;EMPLOYEE BADGE;20144;EMPLOYEE;[B] OPERATOR WATER SUPPLY & DRAINAGE SHIFT;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
430;PF.B1.103;PREFAB B1;TRI ANDIKA SAPUTRA;EMPLOYEE BADGE;20392;EMPLOYEE;[D] OPERATOR WATER SUPPLY & DRAINAGE SHIFT;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
431;PF.B1.104;PREFAB B1;VACANT 1;;;;;;;;;;;;;;;;;;;;;;;
432;PF.B1.104;PREFAB B1;VACANT 2;;;;;;;;;;;;;;;;;;;;;;;
433;PF.B1.104;PREFAB B1;VACANT 3;;;;;;;;;;;;;;;;;;;;;;;
434;PF.B1.105;PREFAB B1;VACANT 1;;;;;;;;;;;;;;;;;;;;;;;
435;PF.B1.105;PREFAB B1;ANGGA PRATAMA SITANGGANG;EMPLOYEE BADGE;20389;EMPLOYEE;[B] OPERATOR WATER CIRCULATING PUMP CHAMBER;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
436;PF.B1.105;PREFAB B1;ANUGRAH;EMPLOYEE BADGE;20135;EMPLOYEE;MASON CREW;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
437;PF.B1.201;PREFAB B1;ISMAIL;EMPLOYEE BADGE;20210;EMPLOYEE;[B] SHIFT MECHANIC;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
438;PF.B1.201;PREFAB B1;ABD. GOFUR;EMPLOYEE BADGE;20184;EMPLOYEE;[B] SHIFT MECHANIC;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
439;PF.B1.201;PREFAB B1;AWALUDDIN;EMPLOYEE BADGE;20164;EMPLOYEE;[C] SHIFT MECHANIC;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
440;PF.B1.202;PREFAB B1;JUNAEDIN;EMPLOYEE BADGE;20212;EMPLOYEE;[C] SHIFT MECHANIC;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
441;PF.B1.202;PREFAB B1;ABDUL TALIF;EMPLOYEE BADGE;20459;EMPLOYEE;[D] SHIFT MECHANIC;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
442;PF.B1.202;PREFAB B1;SYAMSUDDIN;EMPLOYEE BADGE;20179;EMPLOYEE;[B] SHIFT MECHANIC;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
443;PF.B1.203;PREFAB B1;MUHAMMAD IMRAN M;EMPLOYEE BADGE;20461;EMPLOYEE;UTILITIES MECHANIC;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
444;PF.B1.203;PREFAB B1;HENDRIAWAN NURRAHMAN;EMPLOYEE BADGE;20462;EMPLOYEE;UTILITIES INSTRUMENT;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
445;PF.B1.203;PREFAB B1;RINO, ST;EMPLOYEE BADGE;20669;EMPLOYEE;UTILITIES MECHANIC;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
446;PF.B1.204;PREFAB B1;MUHAMMAD IRFAN;EMPLOYEE BADGE;20127;EMPLOYEE;DRYER KILN MECHANIC;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
447;PF.B1.204;PREFAB B1;FAKHRULLAH;EMPLOYEE BADGE;20667;EMPLOYEE;DRYER KILN ELECTRIC;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
448;PF.B1.204;PREFAB B1;MUHAMMAD IQBAL;EMPLOYEE BADGE;20454;EMPLOYEE;DRYER KILN MECHANIC;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
449;PF.B1.205;PREFAB B1;ARYAN SRI HARMANTO LAPOTASI;EMPLOYEE BADGE;20131;EMPLOYEE;FURNACE MECHANICAL;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
450;PF.B1.205;PREFAB B1;MATIUS DUMA;EMPLOYEE BADGE;20630;EMPLOYEE;DRYER KILN ELECTRIC;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
451;PF.B1.205;PREFAB B1;APRI GANNA;EMPLOYEE BADGE;20214;EMPLOYEE;DRYER KILN MECHANIC;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
452;PF.B2.101;PREFAB B2;ADRIANTO;EMPLOYEE BADGE;20608;EMPLOYEE;DRYER KILN MECHANIC;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
453;PF.B2.101;PREFAB B2;IQRA;EMPLOYEE BADGE;20132;EMPLOYEE;FURNACE MECHANICAL;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
454;PF.B2.101;PREFAB B2;MUH. ALGHAZALI GALIB GAE;EMPLOYEE BADGE;20628;EMPLOYEE;FURNACE ELECTRICAL;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
455;PF.B2.102;PREFAB B2;MUHAMMAD HAIRIL;EMPLOYEE BADGE;20464;EMPLOYEE;FURNACE MECHANICAL;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
456;PF.B2.102;PREFAB B2;ASRIADI ARIF;EMPLOYEE BADGE;20618;EMPLOYEE;FURNACE MECHANICAL;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
457;PF.B2.102;PREFAB B2;SYAHRUL, ST;EMPLOYEE BADGE;20635;EMPLOYEE;FURNACE MECHANICAL;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
458;PF.B2.103;PREFAB B2;RACHMAT;EMPLOYEE BADGE;20275;EMPLOYEE;CASING SHOP CREW;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
459;PF.B2.103;PREFAB B2;SUDIRMAN;EMPLOYEE BADGE;20121;EMPLOYEE;CASING SHOP CREW;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
460;PF.B2.103;PREFAB B2;ABD. RAHMAN;EMPLOYEE BADGE;20157;EMPLOYEE;CASING SHOP CREW;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
461;PF.B2.104;PREFAB B2;SUMARDI;EMPLOYEE BADGE;20155;EMPLOYEE;ELECTRO-MECHANICAL CREW (MOTOR, PUMP, REFURBISH OR REPAIR);NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
462;PF.B2.104;PREFAB B2;IHWANUL ANDY HERRY;EMPLOYEE BADGE;20160;EMPLOYEE;ELECTRO-MECHANICAL CREW (MOTOR, PUMP, REFURBISH OR REPAIR);NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
463;PF.B2.104;PREFAB B2;SLAMET RIYADI;EMPLOYEE BADGE;20036;EMPLOYEE;MECHANIC FABRICATOR;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
464;PF.B2.105;PREFAB B2;YUDISTIRAH;EMPLOYEE BADGE;20150;EMPLOYEE;[A] SHIFT MECHANIC;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
465;PF.B2.105;PREFAB B2;ALDY HERMAWAN PUTRA;EMPLOYEE BADGE;20151;EMPLOYEE;[A] SHIFT MECHANIC;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
466;PF.B2.105;PREFAB B2;ZULKIFLI;EMPLOYEE BADGE;20152;EMPLOYEE;[A] SHIFT MECHANIC;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
467;PF.B2.201;PREFAB B2;ANDI YASSER ASMIR;EMPLOYEE BADGE;20123;EMPLOYEE;CASING WELDING;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
468;PF.B2.201;PREFAB B2;AHMAD RAMADAN;EMPLOYEE BADGE;20272;EMPLOYEE;FURNACE MECHANICAL;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
469;PF.B2.201;PREFAB B2;MUH. ALI IMRAN;EMPLOYEE BADGE;20828;EMPLOYEE;[FS] WELDER;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
470;PF.B2.202;PREFAB B2;YANSEN TANGIBALI PARERUNGAN;EMPLOYEE BADGE;20458;EMPLOYEE;FURNACE MECHANICAL;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
471;PF.B2.202;PREFAB B2;SEDNY TIKU PADANG;EMPLOYEE BADGE;20215;EMPLOYEE;FURNACE ELECTRICAL;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
472;PF.B2.202;PREFAB B2;RANDI MANGIDING;EMPLOYEE BADGE;20470;EMPLOYEE;FURNACE INSTRUMENT;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
473;PF.B2.203;PREFAB B2;ILHAM;EMPLOYEE BADGE;20629;EMPLOYEE;FURNACE ELECTRICAL;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
474;PF.B2.203;PREFAB B2;MUHAMAD HADRAL HAQ;EMPLOYEE BADGE;20698;EMPLOYEE;FURNACE INSTRUMENT;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
475;PF.B2.203;PREFAB B2;HENDRA SUFRI;EMPLOYEE BADGE;20699;EMPLOYEE;FURNACE ELECTRICAL;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
476;PF.B2.204;PREFAB B2;BAHAR MUHARRAM;EMPLOYEE BADGE;20145;EMPLOYEE;[B] SHIFT MECHANIC;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
477;PF.B2.204;PREFAB B2;DARMAWAN HIDAYAT;EMPLOYEE BADGE;20460;EMPLOYEE;[B] SHIFT ELECTRIC;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
478;PF.B2.204;PREFAB B2;S. EFENDI;EMPLOYEE BADGE;20617;EMPLOYEE;[D] SHIFT ELECTRIC;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
479;PF.B2.205;PREFAB B2;SYAHRUL GUNAWAN;EMPLOYEE BADGE;20356;EMPLOYEE;CASING SHOP CREW;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
480;PF.B2.205;PREFAB B2;ADRIAN;EMPLOYEE BADGE;20273;EMPLOYEE;MACHINIST;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
481;PF.B2.205;PREFAB B2;MUH RIZKY AWINDA PUTRA;EMPLOYEE BADGE;20700;EMPLOYEE;[C] SHIFT INSTRUMENT;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
482;PF.C1.101;PREFAB C1;AGUS MUNANDAR;EMPLOYEE BADGE;20733;EMPLOYEE;[B] SHIFT ELECTRIC;NON STAFF - OPERATOR;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
483;PF.C1.101;PREFAB C1;PRASTOWO;EMPLOYEE BADGE;20747;EMPLOYEE;[FS] WELDER;NON STAFF - OPERATOR;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
484;PF.C1.101;PREFAB C1;PAGLI WANDA PENDI PALALLO;EMPLOYEE BADGE;20721;EMPLOYEE;LABORATORY & SAMPLE PREPARATION;NON STAFF - OPERATOR;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
485;PF.C1.102;PREFAB C1;SUKMA DWI PRAKASA;EMPLOYEE BADGE;20303;EMPLOYEE;[A] LAB ANALYST;NON STAFF - OPERATOR;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
486;PF.C1.102;PREFAB C1;MUH. IKBAL;EMPLOYEE BADGE;20220;EMPLOYEE;OPERATOR 1 LABORATORY & SAMPLE PREPARATION;NON STAFF - OPERATOR;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
487;PF.C1.102;PREFAB C1;SYAM HIDAYATULLAH;EMPLOYEE BADGE;20318;EMPLOYEE;MASTER LABORATORY & SAMPLE PREPARATION;NON STAFF - OPERATOR;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
488;PF.C1.103;PREFAB C1;ARDYANZHA SYARIFUDDIN;EMPLOYEE BADGE;20222;EMPLOYEE;MASTER LABORATORY & SAMPLE PREPARATION;NON STAFF - OPERATOR;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
489;PF.C1.103;PREFAB C1;EDO CHANDRA HARYANTO;EMPLOYEE BADGE;20221;EMPLOYEE;OPERATOR 1 LABORATORY & SAMPLE PREPARATION;NON STAFF - OPERATOR;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
490;PF.C1.103;PREFAB C1;MUHAMMAD RAMADHAN;EMPLOYEE BADGE;20695;EMPLOYEE;DRYER KILN INSTRUMENT;NON STAFF - OPERATOR;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
491;PF.C1.104;PREFAB C1;MARCELINUS B;EMPLOYEE BADGE;20217;EMPLOYEE;OPERATOR 1 LABORATORY & SAMPLE PREPARATION;NON STAFF - OPERATOR;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
492;PF.C1.104;PREFAB C1;HADIRMAN S;EMPLOYEE BADGE;20218;EMPLOYEE;MASTER LABORATORY & SAMPLE PREPARATION;NON STAFF - OPERATOR;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
493;PF.C1.104;PREFAB C1;SULHAN;EMPLOYEE BADGE;20219;EMPLOYEE;OPERATOR 1 LABORATORY & SAMPLE PREPARATION;NON STAFF - OPERATOR;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
494;PF.C1.105;PREFAB C1;LUKMAN;EMPLOYEE BADGE;20744;EMPLOYEE;[FS] WELDER;NON STAFF - OPERATOR;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
495;PF.C1.105;PREFAB C1;SYAHRUL SYAMSUDDIN;EMPLOYEE BADGE;20745;EMPLOYEE;[FS] WELDER;NON STAFF - OPERATOR;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
496;PF.C1.105;PREFAB C1;REVIT;EMPLOYEE BADGE;20746;EMPLOYEE;[FS] WELDER;NON STAFF - OPERATOR;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
497;PF.C1.201;PREFAB C1;AHMAD ARIF ISMAIL A.;EMPLOYEE BADGE;20703;EMPLOYEE;[D] SHIFT INSTRUMENT;NON STAFF - OPERATOR;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
498;PF.C1.201;PREFAB C1;MUH. ARIGI RAMADHANA;EMPLOYEE BADGE;20715;EMPLOYEE;DRYER KILN INSTRUMENT;NON STAFF - OPERATOR;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
499;PF.C1.201;PREFAB C1;ANDI MUAMMAR NUGRAHA;EMPLOYEE BADGE;20696;EMPLOYEE;[D] SHIFT INSTRUMENT;NON STAFF - OPERATOR;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
500;PF.C1.202;PREFAB C1;ANUGRAH;EMPLOYEE BADGE;20135;EMPLOYEE;MASON CREW;NON STAFF - OPERATOR;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
501;PF.C1.202;PREFAB C1;FIRMAN SYAH;EMPLOYEE BADGE;20723;EMPLOYEE;MASON CREW;NON STAFF - OPERATOR;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
502;PF.C1.202;PREFAB C1;RISAL EFENDY;EMPLOYEE BADGE;20139;EMPLOYEE;MASON CREW;NON STAFF - OPERATOR;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
503;PF.C1.203;PREFAB C1;FAISAL;EMPLOYEE BADGE;20136;EMPLOYEE;MASON CREW;NON STAFF - OPERATOR;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
504;PF.C1.203;PREFAB C1;ARFAH BURHAN;EMPLOYEE BADGE;20138;EMPLOYEE;MASON CREW;NON STAFF - OPERATOR;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
505;PF.C1.203;PREFAB C1;ARHAM;EMPLOYEE BADGE;20137;EMPLOYEE;MASON CREW;NON STAFF - OPERATOR;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
506;PF.C1.204;PREFAB C1;IMRAN KARIM;EMPLOYEE BADGE;20758;EMPLOYEE;MECHANIC FABRICATOR;NON STAFF - OPERATOR;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
507;PF.C1.204;PREFAB C1;SABARULLAH HALI;EMPLOYEE BADGE;20757;EMPLOYEE;[A] SHIFT ELECTRIC;NON STAFF - OPERATOR;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
508;PF.C1.204;PREFAB C1;RUDI HARTONO;EMPLOYEE BADGE;20763;EMPLOYEE;[EC] WELDER;NON STAFF - OPERATOR;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
509;PF.C1.205;PREFAB C1;FERDIANUS PUTRA TANGNGA;EMPLOYEE BADGE;20720;EMPLOYEE;MACHINIST;NON STAFF - OPERATOR;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
510;PF.C1.205;PREFAB C1;MUH. AZHAR;EMPLOYEE BADGE;20729;EMPLOYEE;[A] SHIFT ELECTRIC;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
511;PF.C1.205;PREFAB C1;IRMAN, S.H;EMPLOYEE BADGE;20690;EMPLOYEE;[B] FEED AREA OPERATOR;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
512;PF.C2.101;PREFAB C2;ASLANG;EMPLOYEE BADGE;20280;EMPLOYEE;[B] OPERATOR ALL ROUND FURNACE;NON STAFF - OPERATOR;PP - FURNACE;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
513;PF.C2.101;PREFAB C2;MUH. RAHUL SAPUTRA;EMPLOYEE BADGE;20232;EMPLOYEE;[B] OPERATOR FEED AREA FURNACE;NON STAFF - OPERATOR;PP - FURNACE;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
514;PF.C2.101;PREFAB C2;SAKKIR;EMPLOYEE BADGE;20252;EMPLOYEE;[B] MASTER OPERATOR WATER CHECKER FURNACE;NON STAFF - OPERATOR;PP - FURNACE;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
515;PF.C2.102;PREFAB C2;AHMAD AVICENNA IBNU RAHMAN;EMPLOYEE BADGE;20253;EMPLOYEE;[C] MASTER OPERATOR TAPPING FURNACE;NON STAFF - OPERATOR;PP - FURNACE;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
516;PF.C2.102;PREFAB C2;SYAMSUL RIJAL;EMPLOYEE BADGE;20256;EMPLOYEE;[C] OPERATOR TAPPING FURNACE;NON STAFF - OPERATOR;PP - FURNACE;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
517;PF.C2.102;PREFAB C2;ASRUL IRAWAN BAHARUDDIN;EMPLOYEE BADGE;20296;EMPLOYEE;[C] OPERATOR PACKAGING;NON STAFF - OPERATOR;PP - FURNACE;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
518;PF.C2.103;PREFAB C2;ALVANDO RANTANG;EMPLOYEE BADGE;20257;EMPLOYEE;[D] MASTER OPERATOR TAPPING FURNACE;NON STAFF - OPERATOR;PP - FURNACE;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
519;PF.C2.103;PREFAB C2;ILHAM;EMPLOYEE BADGE;20239;EMPLOYEE;[D] OPERATOR SKIMMING FURNACE;NON STAFF - OPERATOR;PP - FURNACE;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
520;PF.C2.103;PREFAB C2;MUHAMMAD IMAN;EMPLOYEE BADGE;20227;EMPLOYEE;[D] OPERATOR CASTING;NON STAFF - OPERATOR;PP - FURNACE;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
521;PF.C2.104;PREFAB C2;IRWANTO IDRIS;EMPLOYEE BADGE;20223;EMPLOYEE;[A] MASTER OPERATOR ALL ROUND FURNACE;NON STAFF - OPERATOR;PP - FURNACE;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
522;PF.C2.104;PREFAB C2;RIAN M;EMPLOYEE BADGE;20235;EMPLOYEE;[A] MASTER OPERATOR PACKAGING;NON STAFF - OPERATOR;PP - FURNACE;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
523;PF.C2.104;PREFAB C2;AHMAD YANI;EMPLOYEE BADGE;20224;EMPLOYEE;MASTER OPERATOR HOT METAL CRANE;NON STAFF - OPERATOR;PP - FURNACE;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
524;PF.C2.105;PREFAB C2;MANDARI DAVID NATANAEL;EMPLOYEE BADGE;20255;EMPLOYEE;[B] OPERATOR CASTING;NON STAFF - OPERATOR;PP - FURNACE;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
525;PF.C2.105;PREFAB C2;HAIRUDDIN;EMPLOYEE BADGE;20234;EMPLOYEE;[B] MASTER OPERATOR PACKAGING;NON STAFF - OPERATOR;PP - FURNACE;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
526;PF.C2.105;PREFAB C2;FAHRUDDIN;EMPLOYEE BADGE;20305;EMPLOYEE;[B] OPERATOR HOT METAL CRANE;NON STAFF - OPERATOR;PP - FURNACE;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
527;PF.C2.201;PREFAB C2;KASMAN;EMPLOYEE BADGE;20260;EMPLOYEE;[B] OPERATOR TAPPING FURNACE;NON STAFF - OPERATOR;PP - FURNACE;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
528;PF.C2.201;PREFAB C2;MAS'UD KAMAL;EMPLOYEE BADGE;20228;EMPLOYEE;[B] OPERATOR CLAMPSHELL FURNACE;NON STAFF - OPERATOR;PP - FURNACE;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
529;PF.C2.201;PREFAB C2;MUHAMMAD ALFIAN ARMEDI;EMPLOYEE BADGE;20259;EMPLOYEE;[B] OPERATOR TAPPING FURNACE;NON STAFF - OPERATOR;PP - FURNACE;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
530;PF.C2.202;PREFAB C2;ERIK ISTIAWAN;EMPLOYEE BADGE;20283;EMPLOYEE;[C] OPERATOR CASTING;NON STAFF - OPERATOR;PP - FURNACE;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
531;PF.C2.202;PREFAB C2;FRENKY PRANATA;EMPLOYEE BADGE;20244;EMPLOYEE;[C] OPERATOR SKIMMING FURNACE;NON STAFF - OPERATOR;PP - FURNACE;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
532;PF.C2.202;PREFAB C2;ZAINUDDIN;EMPLOYEE BADGE;20247;EMPLOYEE;[C] MASTER OPERATOR SKIMMING FURNACE;NON STAFF - OPERATOR;PP - FURNACE;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
533;PF.C2.203;PREFAB C2;MADE DEDY SANJAYA;EMPLOYEE BADGE;20254;EMPLOYEE;[A] MASTER OPERATOR CLAMPSHELL FURNACE;NON STAFF - OPERATOR;PP - FURNACE;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
534;PF.C2.203;PREFAB C2;ASWAR ANAS;EMPLOYEE BADGE;20266;EMPLOYEE;[A] MASTER OPERATOR WATER CHECKER FURNACE;NON STAFF - OPERATOR;PP - FURNACE;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
535;PF.C2.203;PREFAB C2;REGI PEBRIAN;EMPLOYEE BADGE;20706;EMPLOYEE;[B] OPERATOR HOT METAL CRANE;NON STAFF - OPERATOR;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
536;PF.C2.204;PREFAB C2;YUSRIL MAHENDRA;EMPLOYEE BADGE;20819;EMPLOYEE;[D] LADLE FURNACE OPERATOR;NON STAFF - OPERATOR;PP - FURNACE;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
537;PF.C2.204;PREFAB C2;RISWANDI;EMPLOYEE BADGE;20304;EMPLOYEE;[C] OPERATOR ALL ROUND FURNACE;NON STAFF - OPERATOR;PP - FURNACE;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
538;PF.C2.204;PREFAB C2;EARWIN ASRUL HARIMU;EMPLOYEE BADGE;20233;EMPLOYEE;[D] MASTER OPERATOR FEED AREA REDUCTION KILN;NON STAFF - OPERATOR;PP - FURNACE;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
539;PF.C2.205;PREFAB C2;ANDRI RINALDI;EMPLOYEE BADGE;20295;EMPLOYEE;[FS] SUPPORT STEADY DAY OPERATOR;NON STAFF - OPERATOR;PP - FURNACE;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
540;PF.C2.205;PREFAB C2;SUHARDI;EMPLOYEE BADGE;20125;EMPLOYEE;DRYER KILN MECHANIC;NON STAFF - OPERATOR;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
541;PF.C2.205;PREFAB C2;HENDRIKUS TEGALION;EMPLOYEE BADGE;20624;EMPLOYEE;[D] OPERATOR TAPPING FURNACE;NON STAFF - OPERATOR;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
542;PF.D1.101;PREFAB D1;FADLY;EMPLOYEE BADGE;20537;EMPLOYEE;DRYER KILN ELECTRIC;NON STAFF - OPERATOR;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
543;PF.D1.101;PREFAB D1;EDI HALIM;EMPLOYEE BADGE;20784;EMPLOYEE;[EC] WELDER;NON STAFF - OPERATOR;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
544;PF.D1.101;PREFAB D1;SAHARUDDIN;;;;WELDER;NON STAFF - OPERATOR;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
545;PF.D1.102;PREFAB D1;MUHAMMAD ARIFANDI;EMPLOYEE BADGE;20792;EMPLOYEE;CASING WELDING;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
546;PF.D1.102;PREFAB D1;MOHAMMAD RASDI NOOR;EMPLOYEE BADGE;20791;EMPLOYEE;[C] SHIFT INSTRUMENT;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
547;PF.D1.102;PREFAB D1;ASGAR;EMPLOYEE BADGE;20786;EMPLOYEE;[EC] WELDER;NON STAFF - OPERATOR;HSE;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
548;PF.D1.103;PREFAB D1;ROSLAN;EMPLOYEE BADGE;20290;EMPLOYEE;[A] OPERATOR FEED AREA REDUCTION KILN;NON STAFF - OPERATOR;PP - DRYER;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
549;PF.D1.103;PREFAB D1;MUHAMMAD ARAS;EMPLOYEE BADGE;20288;EMPLOYEE;[A] OPERATOR DISCHARGE END;NON STAFF - OPERATOR;PP - DRYER;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
550;PF.D1.103;PREFAB D1;WAHYU ANDIKA;EMPLOYEE BADGE;20225;EMPLOYEE;MASTER OPERATOR ALL ROUND KILN & CTS;NON STAFF - OPERATOR;PP - DRYER;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
551;PF.D1.104;PREFAB D1;ADI JUMADI;EMPLOYEE BADGE;20291;EMPLOYEE;[B] OPERATOR DISCHARGE END;NON STAFF - OPERATOR;PP - DRYER;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
552;PF.D1.104;PREFAB D1;IRSAN GAFFAR;EMPLOYEE BADGE;20289;EMPLOYEE;[B] OPERATOR DUST HANDLING;NON STAFF - OPERATOR;PP - DRYER;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
553;PF.D1.104;PREFAB D1;HAERUDDIN RAHMAN;EMPLOYEE BADGE;20293;EMPLOYEE;MASTER OPERATOR DUST HANDLING;NON STAFF - OPERATOR;PP - DRYER;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
554;PF.D1.105;PREFAB D1;AGUNG SYAMSUDDIN;EMPLOYEE BADGE;20281;EMPLOYEE;[C] OPERATOR CALCINE CRANE;NON STAFF - OPERATOR;PP - DRYER;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
555;PF.D1.105;PREFAB D1;ROBER PAYANGAN;EMPLOYEE BADGE;20292;EMPLOYEE;[C] OPERATOR DUST HANDLING;NON STAFF - OPERATOR;PP - DRYER;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
556;PF.D1.105;PREFAB D1;DULMAN;EMPLOYEE BADGE;20294;EMPLOYEE;[C] OPERATOR DUST HANDLING;NON STAFF - OPERATOR;PP - DRYER;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
557;PF.D1.201;PREFAB D1;EARWIN ASRUL HARIMU;EMPLOYEE BADGE;20233;EMPLOYEE;[D] MASTER OPERATOR FEED AREA REDUCTION KILN;NON STAFF - OPERATOR;PP - DRYER;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
558;PF.D1.201;PREFAB D1;M. MUJAHIDIN ILMAN YASIN;EMPLOYEE BADGE;20362;EMPLOYEE;[D] OPERATOR DISCHARGE END;NON STAFF - OPERATOR;PP - DRYER;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
559;PF.D1.201;PREFAB D1;MUSLIM;EMPLOYEE BADGE;20363;EMPLOYEE;[D] OPERATOR DUST HANDLING;NON STAFF - OPERATOR;PP - DRYER;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
560;PF.D1.202;PREFAB D1;AENUL YAKIN;EMPLOYEE BADGE;20226;EMPLOYEE;[A] OPERATOR CALCINE CRANE;NON STAFF - OPERATOR;PP - DRYER;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
561;PF.D1.202;PREFAB D1;SUTRISNA;EMPLOYEE BADGE;20262;EMPLOYEE;[A] OPERATOR DUST HANDLING;NON STAFF - OPERATOR;PP - DRYER;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
562;PF.D1.202;PREFAB D1;ASRIADI DAMING;EMPLOYEE BADGE;20263;EMPLOYEE;[A] OPERATOR DUST HANDLING;NON STAFF - OPERATOR;PP - DRYER;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
563;PF.D1.203;PREFAB D1;ASDAR;EMPLOYEE BADGE;20797;EMPLOYEE;[A] OPERATOR HOT METAL CRANE;NON STAFF - OPERATOR;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
564;PF.D1.203;PREFAB D1;ALFA RABI;EMPLOYEE BADGE;20417;EMPLOYEE;[B] OPERATOR ALL ROUND REDUCTION KILN;NON STAFF - OPERATOR;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
565;PF.D1.203;PREFAB D1;JUSWAN;EMPLOYEE BADGE;20689;EMPLOYEE;[B] OPERATOR FEED AREA REDUCTION KILN;NON STAFF - OPERATOR;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
566;PF.D1.204;PREFAB D1;MUH. SAHDAN;EMPLOYEE BADGE;20407;EMPLOYEE;[C] OPERATOR FEED AREA REDUCTION KILN;NON STAFF - OPERATOR;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
567;PF.D1.204;PREFAB D1;SANDHI HARYADI S;EMPLOYEE BADGE;20400;EMPLOYEE;[C] OPERATOR DISCHARGE END;NON STAFF - OPERATOR;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
568;PF.D1.204;PREFAB D1;ZULFIKAR TORESANO;EMPLOYEE BADGE;20405;EMPLOYEE;[C] MASTER OPERATOR ALL ROUND REDUCTION KILN;NON STAFF - OPERATOR;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
569;PF.D1.205;PREFAB D1;ISHA SAENAL;EMPLOYEE BADGE;20282;EMPLOYEE;[D] OPERATOR CALCINE CRANE;NON STAFF - OPERATOR;PP - DRYER;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
570;PF.D1.205;PREFAB D1;FIRMINUS JENI PULU;EMPLOYEE BADGE;20435;EMPLOYEE;[D] MASTER OPERATOR ALL ROUND REDUCTION KILN;NON STAFF - OPERATOR;PP - DRYER;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
571;PF.D1.205;PREFAB D1;MUH. RIJAL;EMPLOYEE BADGE;20399;EMPLOYEE;[D] OPERATOR DUST HANDLING;NON STAFF - OPERATOR;PP - DRYER;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
572;PF.D2.101;PREFAB D2;MUHAMMAD JUANNA IDRIS;EMPLOYEE BADGE;20267;EMPLOYEE;FURNACE MECHANICAL;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
573;PF.D2.101;PREFAB D2;ANDI ILHAMSYAH;EMPLOYEE BADGE;20133;EMPLOYEE;FURNACE MECHANICAL;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
574;PF.D2.101;PREFAB D2;PRAYOGO BUDIMAN, S.Tr.T;EMPLOYEE BADGE;20654;EMPLOYEE;FURNACE INSTRUMENT;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
575;PF.D2.102;PREFAB D2;JUNAEDI;EMPLOYEE BADGE;20147;EMPLOYEE;[B] SHIFT INSTRUMENT;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
576;PF.D2.102;PREFAB D2;AKZYAWAL;EMPLOYEE BADGE;20130;EMPLOYEE;FURNACE ELECTRICAL;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
577;PF.D2.102;PREFAB D2;MUHAMMAD KHALIL HAJID;EMPLOYEE BADGE;20463;EMPLOYEE;[C] SHIFT ELECTRIC;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
578;PF.D2.103;PREFAB D2;CHEVIN ANTHONIO LEANDRO;EMPLOYEE BADGE;20653;EMPLOYEE;DRYER KILN INSTRUMENT;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
579;PF.D2.103;PREFAB D2;SAMSIR ARIFUDDIN;EMPLOYEE BADGE;20631;EMPLOYEE;ELECTRODE CASING FIELD SUPERVISOR;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
580;PF.D2.103;PREFAB D2;YEYEN;EMPLOYEE BADGE;20149;EMPLOYEE;[A] SHIFT MECHANIC;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
581;PF.D2.104;PREFAB D2;SYAWAL;EMPLOYEE BADGE;20213;EMPLOYEE;FURNACE ELECTRICAL;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
582;PF.D2.104;PREFAB D2;FIRMANSYAH T;EMPLOYEE BADGE;20625;EMPLOYEE;[A] COAL MILL OPERATOR;NON STAFF - OPERATOR;PP - DRYER;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
583;PF.D2.104;PREFAB D2;FAHRUL;EMPLOYEE BADGE;20626;EMPLOYEE;[A] COAL MILL OPERATOR;NON STAFF - OPERATOR;PP - DRYER;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
584;PF.D2.105;PREFAB D2;ABDILLAH ALIMUDDIN;EMPLOYEE BADGE;20319;EMPLOYEE;[RK] SUPPORT STEADY DAY OPERATOR;NON STAFF - OPERATOR;PP - DRYER;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
585;PF.D2.105;PREFAB D2;AGUNG IZZULHAQ;EMPLOYEE BADGE;20425;EMPLOYEE;[RK] SUPPORT STEADY DAY OPERATOR;NON STAFF - OPERATOR;PP - DRYER;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
586;PF.D2.105;PREFAB D2;HESRON STEVEN MARTHEN BIU;EMPLOYEE BADGE;20670;EMPLOYEE;[A] OPERATOR ALL ROUND DRYER;NON STAFF - OPERATOR;PP - DRYER;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
587;PF.D2.201;PREFAB D2;FAUSAN AL KHAERY;EMPLOYEE BADGE;20676;EMPLOYEE;[B] COAL MILL OPERATOR;NON STAFF - OPERATOR;PP - DRYER;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
588;PF.D2.201;PREFAB D2;NUR SOFYAN;EMPLOYEE BADGE;20373;EMPLOYEE;[C] OPERATOR PRODUCT AREA DRYER;NON STAFF - OPERATOR;PP - DRYER;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
589;PF.D2.201;PREFAB D2;YORIM JONI SANTO;EMPLOYEE BADGE;20424;EMPLOYEE;[A] COAL MILL OPERATOR;NON STAFF - OPERATOR;PP - DRYER;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
590;PF.D2.202;PREFAB D2;AGUNG ASMARA;EMPLOYEE BADGE;20299;EMPLOYEE;[DT] SUPPORT STEADY DAY OPERATOR;NON STAFF - OPERATOR;PP - DRYER;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
591;PF.D2.202;PREFAB D2;YERI ALVIANTO;EMPLOYEE BADGE;20313;EMPLOYEE;[C] COAL MILL OPERATOR;NON STAFF - OPERATOR;PP - DRYER;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
592;PF.D2.202;PREFAB D2;SABARULLAH HALI;EMPLOYEE BADGE;20757;EMPLOYEE;[A] SHIFT ELECTRIC;NON STAFF - OPERATOR;PP - DRYER;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
593;PF.D2.203;PREFAB D2;MUH IRSANDI ADWIANTO;EMPLOYEE BADGE;20146;EMPLOYEE;[A] SHIFT INSTRUMENT;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
594;PF.D2.203;PREFAB D2;LUQMAN WALI AHMAD;EMPLOYEE BADGE;20453;EMPLOYEE;[C] SHIFT INSTRUMENT;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
595;PF.D2.203;PREFAB D2;EDY IRWAN;EMPLOYEE BADGE;20668;EMPLOYEE;[D] SHIFT MECHANIC;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
596;PF.D2.204;PREFAB D2;YOEL TATO;EMPLOYEE BADGE;20148;EMPLOYEE;[B] SHIFT MECHANIC;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
597;PF.D2.204;PREFAB D2;LUTER TIBIAN;EMPLOYEE BADGE;20611;EMPLOYEE;[D] SHIFT MECHANIC;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
598;PF.D2.204;PREFAB D2;ARMAN LAPU;EMPLOYEE BADGE;20211;EMPLOYEE;[C] SHIFT MECHANIC;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
599;PF.D2.205;PREFAB D2;RAHADI BARI;EMPLOYEE BADGE;20134;EMPLOYEE;MACHINIST;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
600;PF.D2.205;PREFAB D2;WILLIAM ROMPI;EMPLOYEE BADGE;20120;EMPLOYEE;CASING SHOP CREW;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
601;PF.D2.205;PREFAB D2;JEFRY JAFAR;EMPLOYEE BADGE;20793;EMPLOYEE;FURNACE INSTRUMENT;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
602;PF.E1.101;PREFAB E1;SLAMET PURWANTO;EMPLOYEE BADGE;20312;EMPLOYEE;[C] OPERATOR WATER CHECKER FURNACE;NON STAFF - OPERATOR;PP - FURNACE;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
603;PF.E1.101;PREFAB E1;HARTO SALINDING;EMPLOYEE BADGE;20315;EMPLOYEE;[A] MASTER OPERATOR CASTING;NON STAFF - OPERATOR;PP - FURNACE;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
604;PF.E1.101;PREFAB E1;FAISAL IBRAHIM;EMPLOYEE BADGE;20297;EMPLOYEE;[D] OPERATOR PACKAGING;NON STAFF - OPERATOR;PP - FURNACE;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
605;PF.E1.102;PREFAB E1;ASWINTO;EMPLOYEE BADGE;20306;EMPLOYEE;[C] OPERATOR CLAMPSHELL FURNACE;NON STAFF - OPERATOR;PP - FURNACE;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
606;PF.E1.102;PREFAB E1;MUHAMMAD RAFLI ANANDA;EMPLOYEE BADGE;20243;EMPLOYEE;[A] OPERATOR SKIMMING FURNACE;NON STAFF - OPERATOR;PP - FURNACE;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
607;PF.E1.102;PREFAB E1;ARMAN MAULANA;EMPLOYEE BADGE;20375;EMPLOYEE;[FS] SUPPORT STEADY DAY OPERATOR;NON STAFF - OPERATOR;PP - FURNACE;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
608;PF.E1.103;PREFAB E1;MUHAMMAD MITRA;EMPLOYEE BADGE;20311;EMPLOYEE;[A] OPERATOR TAPPING FURNACE;NON STAFF - OPERATOR;PP - FURNACE;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
609;PF.E1.103;PREFAB E1;HERDI HAMSAH;EMPLOYEE BADGE;20309;EMPLOYEE;[D] OPERATOR ALL ROUND FURNACE;NON STAFF - OPERATOR;PP - FURNACE;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
610;PF.E1.103;PREFAB E1;ILHAM;EMPLOYEE BADGE;20308;EMPLOYEE;[A] OPERATOR TAPPING FURNACE;NON STAFF - OPERATOR;PP - FURNACE;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
611;PF.E1.104;PREFAB E1;NIRMAN IDRIS;EMPLOYEE BADGE;20251;EMPLOYEE;[A] MASTER OPERATOR SKIMMING FURNACE;NON STAFF - OPERATOR;PP - FURNACE;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
612;PF.E1.104;PREFAB E1;TAUFIK;EMPLOYEE BADGE;20245;EMPLOYEE;[A] MASTER OPERATOR SKIMMING FURNACE;NON STAFF - OPERATOR;PP - FURNACE;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
613;PF.E1.104;PREFAB E1;RUDI MIRAJE;EMPLOYEE BADGE;20250;EMPLOYEE;[A] MASTER OPERATOR TAPPING FURNACE;NON STAFF - OPERATOR;PP - FURNACE;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
614;PF.E1.105;PREFAB E1;RINTO ADVENTUS;EMPLOYEE BADGE;20810;EMPLOYEE;[A] OPERATOR HOT METAL CRANE;NON STAFF - OPERATOR;PP - FURNACE;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
615;PF.E1.105;PREFAB E1;ALFONSO TAKA;EMPLOYEE BADGE;20449;EMPLOYEE;[D] MASTER OPERATOR WATER CHECKER FURNACE;NON STAFF - OPERATOR;PP - FURNACE;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
616;PF.E1.105;PREFAB E1;SAHRIN S;EMPLOYEE BADGE;20258;EMPLOYEE;[D] OPERATOR TAPPING FURNACE;NON STAFF - OPERATOR;PP - FURNACE;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
617;PF.E1.201;PREFAB E1;RICHO ARDYAWAN MUNAJAT;EMPLOYEE BADGE;20246;EMPLOYEE;[B] MASTER OPERATOR SKIMMING FURNACE;NON STAFF - OPERATOR;PP - FURNACE;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
618;PF.E1.201;PREFAB E1;ROBERT RADA;EMPLOYEE BADGE;20240;EMPLOYEE;[B] OPERATOR SKIMMING FURNACE;NON STAFF - OPERATOR;PP - FURNACE;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
619;PF.E1.201;PREFAB E1;IMAM RAMADHAN;EMPLOYEE BADGE;20242;EMPLOYEE;[B] OPERATOR SKIMMING FURNACE;NON STAFF - OPERATOR;PP - FURNACE;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
620;PF.E1.202;PREFAB E1;GUNTUR WAHYU;EMPLOYEE BADGE;20403;EMPLOYEE;[C] OPERATOR FEED AREA FURNACE;NON STAFF - OPERATOR;PP - FURNACE;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
621;PF.E1.202;PREFAB E1;RAFLIN;EMPLOYEE BADGE;20231;EMPLOYEE;[A] OPERATOR FEED AREA FURNACE;NON STAFF - OPERATOR;PP - FURNACE;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
622;PF.E1.202;PREFAB E1;JEMES BETA;EMPLOYEE BADGE;20249;EMPLOYEE;[C] MASTER OPERATOR TAPPING FURNACE;NON STAFF - OPERATOR;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
623;PF.E1.203;PREFAB E1;A. TANDRI SUKKY;EMPLOYEE BADGE;20716;EMPLOYEE;[D] OPERATOR FEED AREA FURNACE;NON STAFF - OPERATOR;PP - FURNACE;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
624;PF.E1.203;PREFAB E1;RAHMAT HIDAYAT;EMPLOYEE BADGE;20298;EMPLOYEE;[B] OPERATOR PRODUCT AREA DRYER;NON STAFF - OPERATOR;PP - DRYER;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
625;PF.E1.203;PREFAB E1;SUMARLIN;EMPLOYEE BADGE;20285;EMPLOYEE;[B] COAL MILL OPERATOR;NON STAFF - OPERATOR;PP - DRYER;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
626;PF.E1.204;PREFAB E1;HANS BRIEGEL YOSNAL;EMPLOYEE BADGE;20236;EMPLOYEE;[A] FEED AREA OPERATOR;NON STAFF - OPERATOR;PP - DRYER;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
627;PF.E1.204;PREFAB E1;M YUSRAN R;EMPLOYEE BADGE;20310;EMPLOYEE;[B] FEED AREA OPERATOR;NON STAFF - OPERATOR;PP - DRYER;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
628;PF.E1.204;PREFAB E1;IRHAM;EMPLOYEE BADGE;11082;EMPLOYEE;DRILL CREW;NON STAFF - OPERATOR;PP - DRYER;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
629;PF.E1.205;PREFAB E1;ARNOLDUS ARDIANTO;EMPLOYEE BADGE;20634;EMPLOYEE;UTILITIES INSTRUMENT;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
630;PF.E1.205;PREFAB E1;ASDAR;EMPLOYEE BADGE;10186;EMPLOYEE;CREW FUEL DISTRIBUTION;NON STAFF - OPERATOR;PP - DRYER;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
631;PF.E1.205;PREFAB E1;PAULUS BANNA;EMPLOYEE BADGE;20286;EMPLOYEE;[C] OPERATOR CONTROL ROOM DRYER;NON STAFF - OPERATOR;PP - DRYER;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
632;PF.E2.101;PREFAB E2;MUH. SAFRY H;EMPLOYEE BADGE;20466;EMPLOYEE;[D] OPERATOR OXYGEN PLANT;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
633;PF.E2.101;PREFAB E2;SUWANDI A;EMPLOYEE BADGE;20615;EMPLOYEE;[D] OPERATOR OXYGEN PLANT;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
634;PF.E2.101;PREFAB E2;ISWANDI;EMPLOYEE BADGE;20418;EMPLOYEE;[C] OPERATOR OXYGEN PLANT;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
635;PF.E2.102;PREFAB E2;WALUYO;EMPLOYEE BADGE;20465;EMPLOYEE;[C] OPERATOR OXYGEN PLANT;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
636;PF.E2.102;PREFAB E2;AGUSDAM;EMPLOYEE BADGE;20480;EMPLOYEE;[C] OPERATOR WATER CIRCULATING PUMP CHAMBER;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
637;PF.E2.102;PREFAB E2;BARDIEN ZULVANDI;EMPLOYEE BADGE;20605;EMPLOYEE;[D] OPERATOR WATER CIRCULATING PUMP CHAMBER;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
638;PF.E2.103;PREFAB E2;BADAR SUSILO;EMPLOYEE BADGE;20390;EMPLOYEE;[B] OPERATOR OXYGEN PLANT;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
639;PF.E2.103;PREFAB E2;ISMAIL;EMPLOYEE BADGE;20468;EMPLOYEE;[C] OPERATOR AIR COMPRESSOR (PLANT & INSTRUMENT AIR);NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
640;PF.E2.103;PREFAB E2;ILHAM;EMPLOYEE BADGE;20477;EMPLOYEE;[D] OPERATOR AIR COMPRESSOR (PLANT & INSTRUMENT AIR);NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
641;PF.E2.104;PREFAB E2;MAKSUM;EMPLOYEE BADGE;20124;EMPLOYEE;DRYER KILN MECHANIC;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
642;PF.E2.104;PREFAB E2;SUHARDI;EMPLOYEE BADGE;20125;EMPLOYEE;DRYER KILN MECHANIC;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
643;PF.E2.104;PREFAB E2;ELIESER BATAU;EMPLOYEE BADGE;20126;EMPLOYEE;DRYER KILN MECHANIC;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
644;PF.E2.105;PREFAB E2;ASEP DARUSSALAM;EMPLOYEE BADGE;20154;EMPLOYEE;UTILITIES MECHANIC;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
645;PF.E2.105;PREFAB E2;HERIK DADANG;EMPLOYEE BADGE;20153;EMPLOYEE;UTILITIES ELECTRIC;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
646;PF.E2.105;PREFAB E2;TASMIN TAJUDDIN;EMPLOYEE BADGE;20269;EMPLOYEE;UTILITIES ELECTRIC;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
647;PF.E2.201;PREFAB E2;RYAN NUGRAHA;EMPLOYEE BADGE;20455;EMPLOYEE;DRYER KILN ELECTRIC;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
648;PF.E2.201;PREFAB E2;KRISMAWAN SIMEON;EMPLOYEE BADGE;20610;EMPLOYEE;DRYER KILN ELECTRIC;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
649;PF.E2.201;PREFAB E2;ADRI ARDIANSYAH T. ROLA;EMPLOYEE BADGE;20619;EMPLOYEE;DRYER KILN ELECTRIC;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
650;PF.E2.202;PREFAB E2;MUHAMMAD FAJRY DWISHAPUTRA;EMPLOYEE BADGE;20760;EMPLOYEE;MECHANIC FABRICATOR;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
651;PF.E2.202;PREFAB E2;ADRIANUS R. DASA;EMPLOYEE BADGE;20457;EMPLOYEE;DRYER KILN INSTRUMENT;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
652;PF.E2.202;PREFAB E2;ABD MALIK;EMPLOYEE BADGE;20128;EMPLOYEE;DRYER KILN MECHANIC;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
653;PF.E2.203;PREFAB E2;MOH. YUSRAN;EMPLOYEE BADGE;20129;EMPLOYEE;DRYER KILN MECHANIC;NON STAFF - OPERATOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
654;PF.E2.203;PREFAB E2;SAMSIR;EMPLOYEE BADGE;20229;EMPLOYEE;[A] COAL MILL OPERATOR;NON STAFF - OPERATOR;PP - DRYER;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
655;PF.E2.203;PREFAB E2;BENEDICTUS IWAN;EMPLOYEE BADGE;20230;EMPLOYEE;[D] FEED AREA OPERATOR;NON STAFF - OPERATOR;PP - DRYER;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
656;PF.E2.204;PREFAB E2;SUHARMAN;;;EMPLOYEE;OPERATOR COAL MILL;NON STAFF - OPERATOR;PP - DRYER;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
657;PF.E2.204;PREFAB E2;SAFUDDIN;EMPLOYEE BADGE;20360;EMPLOYEE;[D] COAL MILL OPERATOR;NON STAFF - OPERATOR;PP - DRYER;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
658;PF.E2.204;PREFAB E2;MUHAMMAD RUM ARSYAD;EMPLOYEE BADGE;20361;EMPLOYEE;[D] OPERATOR ALL ROUND DRYER;NON STAFF - OPERATOR;PP - DRYER;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
659;PF.E2.205;PREFAB E2;ARIFUDDIN;EMPLOYEE BADGE;20339;EMPLOYEE;[C] OPERATOR ALL ROUND DRYER;NON STAFF - OPERATOR;PP - DRYER;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
660;PF.E2.205;PREFAB E2;SUHARMAN;EMPLOYEE BADGE;20264;EMPLOYEE;[D] OPERATOR PRODUCT AREA DRYER;NON STAFF - OPERATOR;PP - DRYER;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
661;PF.E2.205;PREFAB E2;RAHMAT SUJUTI;EMPLOYEE BADGE;20316;EMPLOYEE;[C] MASTER FEED AREA OPERATOR;NON STAFF - OPERATOR;PP - DRYER;PT. CMP;REGULAR GUEST;STANDARD BUFFET;LIVING 3 CANTEEN;LIVING 3 CANTEEN;LIVING 3 CANTEEN;;;;;;;;;;;
662;VP.A1-01;MANDO VVIP-A1;;;;;;;;;;;;;;;;;;;;;;;;
663;VP.A1-02;MANDO VVIP-A1;;;;;;;;;;;;;;;;;;;;;;;;
664;VP.A1-03;MANDO VVIP-A1;;;;;;;;;;;;;;;;;;;;;;;;
665;VP.A1-04;MANDO VVIP-A1;;;;;;;;;;;;;;;;;;;;;;;;
666;VP.A2-01;MANDO VVIP-A2;;;;;;;;;;;;;;;;;;;;;;;;
667;VP.A2-02;MANDO VVIP-A2;;;;;;;;;;;;;;;;;;;;;;;;
668;VP.A2-03;MANDO VVIP-A2;;;;;;;;;;;;;;;;;;;;;;;;
669;VP.A2-04;MANDO VVIP-A2;;;;;;;;;;;;;;;;;;;;;;;;
670;MB.01.01;MANADO B1;ANDARIAS PALA BATARA;EMPLOYEE BADGE;10010;EMPLOYEE;COMMUNITY RELATION MANAGER;SR. STAFF - MANAGER;COMMUNITY RELATION;PT. CNI;REGULAR GUEST;STANDARD BUFFET;SAMAENRE CANTEEN;SAMAENRE CANTEEN;SAMAENRE CANTEEN;;;;;;;;;;;
671;MB.01.01;MANADO B1;VACANT ;;;;;;;;;;;;;;;;;;;;;;;
672;MB.01.02;MANADO B1;YOHAN;;;;;;;PT. CNI;REGULAR GUEST;STANDARD BUFFET;SAMAENRE CANTEEN;SAMAENRE CANTEEN;SAMAENRE CANTEEN;;;;;;;;;;;
673;MB.01.02;MANADO B1;SALMAN ACO;;;;;;;;REGULAR GUEST;STANDARD BUFFET;SAMAENRE CANTEEN;SAMAENRE CANTEEN;SAMAENRE CANTEEN;;;;;;;;;;;
674;MB.02.01;MANADO B2;EDY DJONI MARKUS NURSEWAN;EMPLOYEE BADGE;10825;EMPLOYEE;[CNI] SHIPMENT PORT OPERATION & MAINTENANCE GENERAL MANAGER;SR. STAFF - GM & EQUIVALENT;SHIPMENT, PORT OPERATION & MAINTENANCE;PT. CNI;REGULAR GUEST;STANDARD BUFFET;SAMAENRE CANTEEN;SAMAENRE CANTEEN;SAMAENRE CANTEEN;;;;;;;;;;;
675;MB.02.02;MANADO B2;VICTOR T. PARANTEAN;EMPLOYEE BADGE;10646;EMPLOYEE;SHIPMENT & PORT OPERATION MANAGER;SR. STAFF - MANAGER;SHIPMENT, PORT OPERATION & MAINTENANCE;PT. CNI;REGULAR GUEST;STANDARD BUFFET;SAMAENRE CANTEEN;SAMAENRE CANTEEN;SAMAENRE CANTEEN;;;;;;;;;;;
676;MB.03.01;MANADO B3;R. B. SONNY SWASONO;EMPLOYEE BADGE;20008;EMPLOYEE;[CMP] CONSTRUCTION MANAGER;SR. STAFF - MANAGER;PROJECT CONSTRUCTION;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SAMAENRE CANTEEN;SAMAENRE CANTEEN;SAMAENRE CANTEEN;;;;;;;;;;;
677;MB.03.02;MANADO B3;ADRIANTITO SALIM LAMO;EMPLOYEE BADGE;90017;EMPLOYEE;CORPORATE COMMUNICATION MANAGER;SR. STAFF - MANAGER;CORPORATE COMMUNICATION;PT. CNI;SPECIAL GUEST;STANDARD BUFFET;SAMAENRE CANTEEN;SAMAENRE CANTEEN;SAMAENRE CANTEEN;;;;;;;;;;;
678;MB.03.02;MANADO B3;AGUS SATRIA;EMPLOYEE BADGE;10819;EMPLOYEE;MINE SERVICE & SUPPORT MANAGER;SR. STAFF - MANAGER;MINE SERVICE & SUPPORT;PT. CNI;REGULAR GUEST;STANDARD BUFFET;SAMAENRE CANTEEN;SAMAENRE CANTEEN;SAMAENRE CANTEEN;;;;;;;;;;;
679;MB.04.01;MANADO B4;VACANT ;;;;;;;;;;;;;;;;;;;;;;;
680;MB.04.02;MANADO B4;VACANT ;;;;;;;;;;;;;;;;;;;;;;;
681;MB.05.01;MANADO B5;SISWO POEDJI PRIYONO;EMPLOYEE BADGE;10045;EMPLOYEE;[CNI] GUEST HANDLING MANAGER;SR. STAFF - MANAGER;GUEST HANDLING;PT. CNI;REGULAR GUEST;STANDARD BUFFET;SAMAENRE CANTEEN;SAMAENRE CANTEEN;SAMAENRE CANTEEN;;;;;;;;;;;
682;MB.05.02;MANADO B5;VACANT ;;;;;;;;;;;;;;;;;;;;;;;
683;MB.06.01;MANADO B6;ALPI CEKDIN;EMPLOYEE BADGE;10036;EMPLOYEE;HEALTH SAFETY ENVIRONMENT (HSE) AND OPERATION COMPLIANCE GENERAL MANAGER;SR. STAFF - GM & EQUIVALENT;HSE & OPERATION COMPLIANCE;PT. CNI;REGULAR GUEST;STANDARD BUFFET;SAMAENRE CANTEEN;SAMAENRE CANTEEN;SAMAENRE CANTEEN;;;;;;;;;;;
684;MB.06.02;MANADO B6;DHANI ROSA PRATAMA;EMPLOYEE BADGE;10041;EMPLOYEE;PROJECT DEVELOPMENT & MINING MANAGER;SR. STAFF - MANAGER;PROJECT DEVELOPMENT & MINING;PT. CNI;REGULAR GUEST;STANDARD BUFFET;SAMAENRE CANTEEN;SAMAENRE CANTEEN;SAMAENRE CANTEEN;;;;;;;;;;;
685;MC.01.01;MANADO C1;CHANDRA BAMBANG SUMARAH;EMPLOYEE BADGE;10664;EMPLOYEE;MINING OPERATION & SUPPORT SENIOR MANAGER;SR. STAFF - MANAGER;MINE SERVICE & SUPPORT;PT. CNI;REGULAR GUEST;STANDARD BUFFET;SAMAENRE CANTEEN;SAMAENRE CANTEEN;SAMAENRE CANTEEN;;;;;;;;;;;
686;MC.01.02;MANADO C1;M. ARFAH MUSTAFA;EMPLOYEE BADGE;11525;EMPLOYEE;GOVERNMENT RELATION MANAGER;SR. STAFF - MANAGER;GOVERNMENT RELATION;PT. CNI;REGULAR GUEST;STANDARD BUFFET;SAMAENRE CANTEEN;SAMAENRE CANTEEN;SAMAENRE CANTEEN;;;;;;;;;;;
687;MC.02.01;MANADO C2;VACANT;;;;;;;;;;;;;;;;;;;;;;;
688;MC.02.01;MANADO C2;VACANT;;;;;;;;;;;;;;;;;;;;;;;
689;MC.02.02;MANADO C2;VACANT;;;;;;;;;;;;;;;;;;;;;;;
690;MC.02.02;MANADO C2;KARMANTO;EMPLOYEE BADGE;90037;EMPLOYEE;PROJECT DOCUMENTATOR;STAFF;CORPORATE COMMUNICATION;PT. CNI;REGULAR GUEST;STANDARD BUFFET;SAMAENRE CANTEEN;SAMAENRE CANTEEN;SAMAENRE CANTEEN;;;;;;;;;;;
691;MC.03.01;MANADO C3;VACANT;;;;;;;;;;;;;;;;;;;;;;;
692;MC.03.01;MANADO C3;VACANT;;;;;;;;;;;;;;;;;;;;;;;
693;MC.03.02;MANADO C3;VACANT;;;;;;;;;;;;;;;;;;;;;;;
694;MC.03.02;MANADO C3;VACANT;;;;;;;;;;;;;;;;;;;;;;;
695;MC.04.01;MANADO C4;SUHARTO ONGGANG;EMPLOYEE BADGE;10788;EMPLOYEE;SITE OPERATION COMMITTEE;SR. STAFF - GM & EQUIVALENT;OPERATION;PT. CNI;REGULAR GUEST;STANDARD BUFFET;SAMAENRE CANTEEN;SAMAENRE CANTEEN;SAMAENRE CANTEEN;;;;;;;;;;;
696;MC.04.02;MANADO C4;EBONY ANDI LOLO;EMPLOYEE BADGE;10042;EMPLOYEE;DATABASE & ADMIN SUPERINTENDENT;SR. STAFF - SUPERINTENDENT;GOVERNMENT RELATION;PT. CNI;REGULAR GUEST;STANDARD BUFFET;SAMAENRE CANTEEN;SAMAENRE CANTEEN;SAMAENRE CANTEEN;;;;;;;;;;;
697;MC.04.02;MANADO C4;YUDI MOCHAMAD;EMPLOYEE BADGE;10674;EMPLOYEE;[CNI] HC EXCELLENCE & INDUSTRIAL RELATION MANAGER;SR. STAFF - MANAGER;HC EXCELLENCE & INDUSTRIAL RELATION;PT. CNI;SPECIAL GUEST;STANDARD BUFFET;SAMAENRE CANTEEN;SAMAENRE CANTEEN;SAMAENRE CANTEEN;;;;;;;;;;;
698;MC.05.01;MANADO C5;AGUSTINUS LONTOH;EMPLOYEE BADGE;C.128;EMPLOYEE;SMELTER SPECIALIST;SR. STAFF - ENGINEER/ SPECIALIST;OPERATION READINESS SMELTER RKEF;PT. CMP;SPECIAL GUEST;ROOM DELIVERY;STAY MESS;STAY MESS;STAY MESS;;;;;;;;;;;
699;MC.05.01;MANADO C5;INDRA HAEDAR NASIR;EMPLOYEE BADGE;20007;EMPLOYEE;[PROJECT] CIVIL ENGINEER;SR. STAFF - ENGINEER/ SPECIALIST;CONSTRUCTION MANAGEMENT;PT. CMP;SPECIAL GUEST;ROOM DELIVERY;STAY MESS;STAY MESS;STAY MESS;;;;;;;;;;;
700;MC.05.02;MANADO C5;MISHBAHUL UMAM;EMPLOYEE BADGE;10749;EMPLOYEE;QA QC CONSTRUCTION SUPERINTENDENT;SR. STAFF - SUPERINTENDENT;PROJECT DEVELOPMENT & MINING;PT. CNI;REGULAR GUEST;STANDARD BUFFET;;;;;;;;;;;;;;
EOD;

$host = '127.0.0.1';
$db   = 'gfs_akomodasi';
$user = 'root';
$pass = '';

try {
     $pdo = new PDO("mysql:host=$host;dbname=$db;charset=utf8mb4", $user, $pass);
     $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

     $rooms = $pdo->query("SELECT id, room_no FROM rooms")->fetchAll(PDO::FETCH_ASSOC);
     $room_map = [];
     foreach ($rooms as $r) {
         $room_map[$r['room_no']] = $r['id'];
     }

     $lines = explode("\n", trim($csvData));
     $stmt = $pdo->prepare("INSERT INTO guests (room_id, name, personal_identification, reg_id_card, job, position, level_category, department, institution_company, occupants_category, meals_packages, breakfast_dp, lunch_dp, dinner_dp, registered_by, last_registration, remarks) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, NOW(), '')");

     $count = 0;
     foreach ($lines as $line) {
         $line = trim($line);
         if (empty($line) || str_starts_with($line, 'NO;') || str_starts_with($line, ';')) continue;
         
         $cols = explode(";", $line);
         if (count($cols) < 16) continue;

         $room_no = trim($cols[1]);
         if ($room_no === 'DM.A3.115' && strpos($line, 'DORMITORY B1') !== false) {
             $room_no = 'DM.B1.115';
         }
         if (!isset($room_map[$room_no])) {
             continue; // Skip if room doesn't exist
         }

         $stmt->execute([
             $room_map[$room_no],
             trim($cols[3]), // name
             trim($cols[4]), // personal_identification
             trim($cols[5]), // reg_id_card
             trim($cols[6]), // job
             trim($cols[7]), // position
             trim($cols[8]), // level_category
             trim($cols[9]), // department
             trim($cols[10]), // institution_company
             trim($cols[11]), // occupants_category
             trim($cols[12]), // meals_packages
             trim($cols[13]), // breakfast_dp
             trim($cols[14]), // lunch_dp
             trim($cols[15]), // dinner_dp
             'Admin' // registered_by
         ]);
         $count++;
     }
     
     echo "Successfully inserted $count records into the guests table.\n";
     
} catch (\PDOException $e) {
     echo "Error: " . $e->getMessage() . "\n";
}
