<?php
$csvData = <<<EOD
71;DM.A3.106;DORMITORY A3;M. RIZKY SAKTIA IRAWAN;EMPLOYEE BADGE;20406;EMPLOYEE;FURNACE INSTRUMENT SUPERVISOR;STAFF - SUPERVISOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
72;DM.A3.106;DORMITORY A3;TOMMY ZEPISA MAHIDDIN CUTTY;EMPLOYEE BADGE;20276;EMPLOYEE;FIRE & RESCUE SUPERINTENDENT;SR. STAFF - SUPERINTENDENT;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
73;DM.A3.107;DORMITORY A3;NURALIM;EMPLOYEE BADGE;20078;EMPLOYEE;MASON SUPERVISOR;STAFF - SUPERVISOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
74;DM.A3.107;DORMITORY A3;AMALDY LATIEF;EMPLOYEE BADGE;20096;EMPLOYEE;[A] MAINTENANCE SHIFT SUPERVISOR;STAFF - SUPERVISOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
75;DM.A3.108;DORMITORY A3;SYAHRIR HAMSAH;EMPLOYEE BADGE;20740;EMPLOYEE;[A] SHIFT CALCINE TRANSFER SYSTEM (CTS) SUPERVISOR;STAFF - SUPERVISOR;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
76;DM.A3.108;DORMITORY A3;GHAZI LABIB NAUFAL INSAN;EMPLOYEE BADGE;20089;EMPLOYEE;[FS] PROCESS ENGINEER SHIFT;STAFF - ENGINEER/ GEOLOGIST;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
77;DM.A3.109;DORMITORY A3;FREDDY STEPENSON HUTABARAT;EMPLOYEE BADGE;20826;EMPLOYEE;ENVIRONMENT SUPERVISOR;STAFF - SUPERVISOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
78;DM.A3.109;DORMITORY A3;YANCE TANDIPADA;EMPLOYEE BADGE;20469;EMPLOYEE;DRYER KILN INSTRUMENT SUPERVISOR;STAFF - SUPERVISOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
79;DM.A3.110;DORMITORY A3;VACANT 1;;;;;;;;;;;;;;;;;;;;;;;
80;DM.A3.110;DORMITORY A3;VACANT 2;;;;;;;;;;;;;;;;;;;;;;;
81;DM.A3.111;DORMITORY A3;ALEXANDER PALISU;EMPLOYEE BADGE;20161;EMPLOYEE;[A] SHIFT UTILITIES OPERATION SUPERVISOR;STAFF - SUPERVISOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
82;DM.A3.111;DORMITORY A3;YULIANUS;EMPLOYEE BADGE;20162;EMPLOYEE;[B] SHIFT UTILITIES OPERATION SUPERVISOR;STAFF - SUPERVISOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
83;DM.A3.112;DORMITORY A3;LALU PARHAN;EMPLOYEE BADGE;20166;EMPLOYEE;[D] SHIFT FURNACE SUPERVISOR;STAFF - SUPERVISOR;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
84;DM.A3.112;DORMITORY A3;DIDIK DARMADI;EMPLOYEE BADGE;20209;EMPLOYEE;[C] SHIFT REDUCTION KILN SUPERVISOR;STAFF - SUPERVISOR;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
85;DM.A3.113;DORMITORY A3;ARDI;EMPLOYEE BADGE;20119;EMPLOYEE;ELECTRICAL MAINTENANCE UTILITIES SUPERVISOR;STAFF - SUPERVISOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
86;DM.A3.113;DORMITORY A3;SYUKUR HASYIM;EMPLOYEE BADGE;20158;EMPLOYEE;[C] SHIFT UTILITIES OPERATION SUPERVISOR;STAFF - SUPERVISOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
87;DM.A3.114;DORMITORY A3;DANIEL T. TANDILINO;EMPLOYEE BADGE;20396;EMPLOYEE;DRYER KILN ELECTRIC SUPERVISOR;STAFF - SUPERVISOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
88;DM.A3.114;DORMITORY A3;LANGGESA BARUMBUN;EMPLOYEE BADGE;20383;EMPLOYEE;[MU] PLANNER ELECTRICAL OR INSTRUMENT;STAFF - SUPERVISOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
89;DM.A3.115;DORMITORY A3;ENOS MARTHEN;EMPLOYEE BADGE;20052;EMPLOYEE;DRYER KILN MECHANIC SUPERVISOR;STAFF - SUPERVISOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
90;DM.A3.115;DORMITORY A3;LAKKU SAMPETODING;EMPLOYEE BADGE;20202;EMPLOYEE;HOUSING FACILITIES & SERVICES SUPERVISOR;STAFF - SUPERVISOR;SITE GENERAL AFFAIR;PT. CNI;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
91;DM.A3.116;DORMITORY A3;TRY JAYANDI FITRA;EMPLOYEE BADGE;20423;EMPLOYEE;[D] SHIFT CALCINE TRANSFER SYSTEM (CTS) SUPERVISOR;STAFF - SUPERVISOR;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
92;DM.A3.116;DORMITORY A3;ASWAR ANAS;EMPLOYEE BADGE;20266;EMPLOYEE;[A] MASTER OPERATOR WATER CHECKER FURNACE;STAFF - SUPERVISOR;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
93;DM.A3.117;DORMITORY A3;SUWARDI;EMPLOYEE BADGE;20714;EMPLOYEE;[C] SHIFT CASTING & PACKAGING SUPERVISOR;STAFF - SUPERVISOR;HSE;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
94;DM.A3.117;DORMITORY A3;LAKSMANA PUTRA NUSANTARA;EMPLOYEE BADGE;20105;EMPLOYEE;INDUSTRIAL HYGIENE & OCCUPATIONAL HEALTH SUPERVISOR;STAFF - SUPERVISOR;HSE;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
95;DM.A3.118;DORMITORY A3;FRANSISKUS SIKAPANG;EMPLOYEE BADGE;20402;EMPLOYEE;[C] SHIFT CALCINE TRANSFER SYSTEM (CTS) SUPERVISOR;STAFF - SUPERVISOR;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
96;DM.A3.118;DORMITORY A3;ISMAIL. M;EMPLOYEE BADGE;20717;EMPLOYEE;[D] SHIFT BLENDING & DUST PELLETIZATION SUPERVISOR;STAFF - SUPERVISOR;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
97;DM.A3.119;DORMITORY A3;ABD. HALIM SELDY THALIB;EMPLOYEE BADGE;20335;EMPLOYEE;[D] SHIFT UTILITIES OPERATION SUPERVISOR;STAFF - SUPERVISOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
98;DM.A3.119;DORMITORY A3;FAJAR DARMAWAN;EMPLOYEE BADGE;20196;EMPLOYEE;ANALYST ELECTRICAL;STAFF - OFFICER;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
99;DM.A3.120;DORMITORY A3;ACHMAD BAIQUNI;EMPLOYEE BADGE;20203;EMPLOYEE;MECHANICAL, ELECTRICAL, PLUMBING SUPERVISOR;STAFF - SUPERVISOR;PDM;PT. CNI;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
100;DM.A3.120;DORMITORY A3;ABDUL KARIM AR;EMPLOYEE BADGE;20189;EMPLOYEE;AUTOMATION ENGINEER;STAFF - ENGINEER/ GEOLOGIST;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
101;DM.A3.201;DORMITORY A3;AWINURDIN ALWI;EMPLOYEE BADGE;20370;EMPLOYEE;INSTRUCTOR DRYER;STAFF - SUPERVISOR;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
102;DM.A3.201;DORMITORY A3;IRVAN SETIAWAN;EMPLOYEE BADGE;20374;EMPLOYEE;[D] SHIFT DRYER SUPERVISOR;STAFF - SUPERVISOR;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
103;DM.A3.202;DORMITORY A3;JUNAIDI SURABA;EMPLOYEE BADGE;20097;EMPLOYEE;DRAFTMAN ELECTRICAL OR INSTRUMENT;STAFF - SUPERVISOR;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
104;DM.A3.202;DORMITORY A3;ASDIR;EMPLOYEE BADGE;20301;EMPLOYEE;[C] SHIFT PLANT TRANSPORTATION SUPERVISOR;STAFF - SUPERVISOR;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
105;DM.A3.203;DORMITORY A3;VACANT 1;;;;;;;;;;;;;;;;;;;;;;;
106;DM.A3.203;DORMITORY A3;SUBROTO SASMITO UTOMO;EMPLOYEE BADGE;20382;EMPLOYEE;[B] SHIFT BLENDING & DUST PELLETIZATION SUPERVISOR;STAFF - SUPERVISOR;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
107;DM.A3.204;DORMITORY A3;HAMRA;EMPLOYEE BADGE;20174;EMPLOYEE;[A] SHIFT BLENDING & DUST PELLETIZATION SUPERVISOR;STAFF - SUPERVISOR;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
108;DM.A3.204;DORMITORY A3;ANDRI WAHYUDI;EMPLOYEE BADGE;20170;EMPLOYEE;[C] SHIFT FURNACE SUPERVISOR;STAFF - SUPERVISOR;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
109;DM.A3.205;DORMITORY A3;ANDI WAHONO;EMPLOYEE BADGE;20192;EMPLOYEE;[B] SHIFT REDUCTION KILN SUPERVISOR;STAFF - SUPERVISOR;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
110;DM.A3.205;DORMITORY A3;DOMINGGUS T;EMPLOYEE BADGE;20173;EMPLOYEE;[A] SHIFT REDUCTION KILN SUPERVISOR;STAFF - SUPERVISOR;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
111;DM.A3.206;DORMITORY A3;SYARIFUDDIN;EMPLOYEE BADGE;20171;EMPLOYEE;[A] SHIFT CASTING & PACKAGING SUPERVISOR;STAFF - SUPERVISOR;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
112;DM.A3.206;DORMITORY A3;SYAMSUAR;EMPLOYEE BADGE;20095;EMPLOYEE;FABRICATION SHOP SUPERVISOR;STAFF - SUPERVISOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
113;DM.A3.207;DORMITORY A3;RIFANTO KAUNAR;EMPLOYEE BADGE;20384;EMPLOYEE;TRAINING & CERTIFICATION SUPERVISOR;STAFF - SUPERVISOR;HSE;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
114;DM.A3.207;DORMITORY A3;ICHSAN APRIANTO YUSTUS;EMPLOYEE BADGE;20300;EMPLOYEE;[D] SHIFT LABORATORY & SAMPLE PREPARATION SUPERVISOR;STAFF - SUPERVISOR;PROD;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
115;DM.A3.208;DORMITORY A3;DADANG SHOLAHUDIN;EMPLOYEE BADGE;20326;EMPLOYEE;[A] SHIFT DRYER SUPERVISOR;STAFF - SUPERVISOR;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
116;DM.A3.208;DORMITORY A3;IMAN PUJIRAHARJO;EMPLOYEE BADGE;20327;EMPLOYEE;[A] SHIFT PLANT TRANSPORTATION SUPERVISOR;STAFF - SUPERVISOR;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
117;DM.A3.209;DORMITORY A3;IMRAN ADIANTO;EMPLOYEE BADGE;20637;EMPLOYEE;SHIPPING & TRAFFIC ARRANGEMENT SERVICES SUPERVISOR;STAFF - SUPERVISOR;PROD;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
118;DM.A3.209;DORMITORY A3;ROMMEL ERNEST PAKOLO;EMPLOYEE BADGE;20321;EMPLOYEE;[D] SHIFT PLANT TRANSPORTATION SUPERVISOR;STAFF - SUPERVISOR;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
119;DM.A3.210;DORMITORY A3;AZLAN FAKHROZI;EMPLOYEE BADGE;20789;EMPLOYEE;PROCESS DEVELOPMENT SUPERVISOR;STAFF - SUPERVISOR;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
120;DM.A3.210;DORMITORY A3;SYARIFUDDIN;EMPLOYEE BADGE;20177;EMPLOYEE;[B] SHIFT PLANT TRANSPORTATION SUPERVISOR;STAFF - SUPERVISOR;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
121;DM.A3.211;DORMITORY A3;YUDHA DWI KISWANTORO;EMPLOYEE BADGE;20385;EMPLOYEE;[CMP] INSTRUMENT ENGINEER;STAFF - ENGINEER/ GEOLOGIST;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
122;DM.A3.211;DORMITORY A3;MHD HANAFI;EMPLOYEE BADGE;11609;EMPLOYEE;CONSTRUCTION SUPERVISOR;STAFF - SUPERVISOR;PDM;PT. CNI;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
123;DM.A3.212;DORMITORY A3;JUNUBI HARJO;EMPLOYEE BADGE;20175;EMPLOYEE;[B] SHIFT CASTING & PACKAGING SUPERVISOR;STAFF - SUPERVISOR;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
124;DM.A3.212;DORMITORY A3;M. THALIB;EMPLOYEE BADGE;20472;EMPLOYEE;[D] SHIFT CASTING & PACKAGING SUPERVISOR;STAFF - SUPERVISOR;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
125;DM.A3.213;DORMITORY A3;MUH. AFDAL;EMPLOYEE BADGE;20079;EMPLOYEE;[MU] PLANNER MECHANICAL;STAFF - OFFICER;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
126;DM.A3.213;DORMITORY A3;MARSAL ADIKA MURLA;EMPLOYEE BADGE;20199;EMPLOYEE;ANALYST MECHANICAL;STAFF - OFFICER;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
127;DM.A3.214;DORMITORY A3;SABILAH ROSIDIN;EMPLOYEE BADGE;20056;EMPLOYEE;[RK] PROCESS ENGINEER SHIFT;STAFF - ENGINEER/ GEOLOGIST;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
128;DM.A3.214;DORMITORY A3;RAMSES JANJI HASIBUAN;EMPLOYEE BADGE;20839;EMPLOYEE;[RK] PROCESS ENGINEER SHIFT;STAFF - ENGINEER/ GEOLOGIST;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
129;DM.A3.215;DORMITORY A3;SURIADI;EMPLOYEE BADGE;20024;EMPLOYEE;[B] MAINTENANCE SHIFT SUPERVISOR;STAFF - SUPERVISOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
130;DM.A3.215;DORMITORY A3;SLAMET RIADI;EMPLOYEE BADGE;20018;EMPLOYEE;[C] MAINTENANCE SHIFT SUPERVISOR;STAFF - SUPERVISOR;SCM;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
131;DM.A3.216;DORMITORY A3;RICKY MARTIN;EMPLOYEE BADGE;20058;EMPLOYEE;[DT] PROCESS ENGINEER SHIFT;STAFF - ENGINEER/ GEOLOGIST;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
132;DM.A3.216;DORMITORY A3;ARHAM;EMPLOYEE BADGE;20069;EMPLOYEE;[FS] PROCESS ENGINEER SHIFT;STAFF - ENGINEER/ GEOLOGIST;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
133;DM.A3.217;DORMITORY A3;MUHAMAD FAUZI BAEHAKI;EMPLOYEE BADGE;20394;EMPLOYEE;[DT] PROCESS ENGINEER SHIFT;STAFF - ENGINEER/ GEOLOGIST;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
134;DM.A3.217;DORMITORY A3;DEARIZA GIFARI;EMPLOYEE BADGE;20376;EMPLOYEE;[C] SHIFT DRYER SUPERVISOR;STAFF - SUPERVISOR;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
135;DM.A3.218;DORMITORY A3;ALI CHAIDAR ALHADAR;EMPLOYEE BADGE;20355;EMPLOYEE;JUNIOR PLANT PLANNER ENGINEER;STAFF - ENGINEER/ GEOLOGIST;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
136;DM.A3.218;DORMITORY A3;AGGRY FALDO PARANTAK;EMPLOYEE BADGE;20070;EMPLOYEE;[RK] PROCESS ENGINEER SHIFT;STAFF - ENGINEER/ GEOLOGIST;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
137;DM.A3.219;DORMITORY A3;ZETA PUPIS RESKY CANSERO;EMPLOYEE BADGE;20329;EMPLOYEE;[FS] PROCESS ENGINEER SHIFT;STAFF - ENGINEER/ GEOLOGIST;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
138;DM.A3.219;DORMITORY A3;BENYAMIN T. PONGSAPAN;EMPLOYEE BADGE;20065;EMPLOYEE;[DKM] PLANNER ELECTRICAL OR INSTRUMENT;STAFF - OFFICER;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
139;DM.A3.220;DORMITORY A3;M. YUSUF;EMPLOYEE BADGE;20099;EMPLOYEE;MATERIAL COORDINATOR;STAFF - ENGINEER/ GEOLOGIST;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
140;DM.A3.220;DORMITORY A3;BAGUS SUSILO PRAMUWICAKSONO SUSANTO;EMPLOYEE BADGE;20180;EMPLOYEE;RELIABILITY ENGINEER;STAFF - ENGINEER/ GEOLOGIST;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
141;DM.B1.101;DORMITORY B1;KIRENIA KARTIKA;EMPLOYEE BADGE;20790;EMPLOYEE;PLANNER ENGINEERING & RELIABILITY;STAFF - OFFICER;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
142;DM.B1.101;DORMITORY B1;TIFANI AULYA;EMPLOYEE BADGE;20178;EMPLOYEE;ASSAY ANALYST;STAFF - OFFICER;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
143;DM.B1.102;DORMITORY B1;NURUL SAKINAH;EMPLOYEE BADGE;20825;EMPLOYEE;DRAFTMAN MECHANICAL OR CIVIL;STAFF - SUPERVISOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
144;DM.B1.102;DORMITORY B1;AINI SUSANTO;EMPLOYEE BADGE;20649;EMPLOYEE;HUMAN CAPITAL BUSINESS PARTNER & INDUSTRIAL RELATION OFFICER;STAFF - OFFICER;HC;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
145;DM.B1.103;DORMITORY B1;SUCI KUSUMANINGSIH;EMPLOYEE BADGE;20277;EMPLOYEE;SAFETY ASSOCIATE;STAFF - OFFICER;HSE;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
146;DM.B1.103;DORMITORY B1;SITI DWI NUGRAHARINI;EMPLOYEE BADGE;20345;EMPLOYEE;DRAFTMAN ELECTRICAL OR INSTRUMENT;STAFF - OFFICER;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
147;DM.B1.104;DORMITORY B1;THERESIA MAXI BINASTI;EMPLOYEE BADGE;20322;EMPLOYEE;[D] LAB ANALYST;NON STAFF;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
148;DM.B1.104;DORMITORY B1;SARIYANTI;EMPLOYEE BADGE;20156;EMPLOYEE;TECH ADMIN (PROCESS PLANT MAINTENANCE);NON STAFF;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
149;DM.B1.104;DORMITORY B1;REZKI SARNI YULIANTI;EMPLOYEE BADGE;20317;EMPLOYEE;[B] LAB ANALYST;NON STAFF;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
150;DM.B1.105;DORMITORY B1;ULFA TIANI LARIO;EMPLOYEE BADGE;20710;EMPLOYEE;CUSTOM ADMIN;STAFF - OFFICER;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
151;DM.B1.105;DORMITORY B1;NANDITA ARDRAFITRI SARASWATI;EMPLOYEE BADGE;20475;EMPLOYEE;SAFETY OFFICER;STAFF - OFFICER;HSE;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
152;DM.B1.106;DORMITORY B1;ANDI FIRDA ISLAMIAH;EMPLOYEE BADGE;20342;EMPLOYEE;[C] SHIFT LABORATORY & SAMPLE PREPARATION SUPERVISOR;STAFF - SUPERVISOR;PROD;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
153;DM.B1.106;DORMITORY B1;NANDA ERZHIAVICA TAMA;EMPLOYEE BADGE;20348;EMPLOYEE;AUTOMATION ENGINEER;STAFF - ENGINEER/ GEOLOGIST;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
154;DM.B1.107;DORMITORY B1;NIKEN;EMPLOYEE BADGE;20754;EMPLOYEE;MANDARIN INTEPRETERS (SHIFT);STAFF - OFFICER;HC ;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
155;DM.B1.107;DORMITORY B1;NIKMAHTUL EVIANA;EMPLOYEE BADGE;20331;EMPLOYEE;[C] LAB ANALYST;NON STAFF;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
156;DM.B1.107;DORMITORY B1;AULIYANI;EMPLOYEE BADGE;20163;EMPLOYEE;TECH ADMIN (UERF);NON STAFF;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
157;DM.B1.108;DORMITORY B1;HASLINDA;EMPLOYEE BADGE;10173;EMPLOYEE;LAUNDRY;STAFF - OFFICER;SITE GENERAL AFFAIR;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
158;DM.B1.108;DORMITORY B1;SURIANI DARRI;EMPLOYEE BADGE;20702;EMPLOYEE;MANDARIN INTEPRETERS (SHIFT);STAFF - OFFICER;HC;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
159;DM.B1.108;DORMITORY B1;ANNISA;EMPLOYEE BADGE;20712;EMPLOYEE;MANDARIN INTEPRETERS (SHIFT);STAFF - OFFICER;HC;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
160;DM.B1.109;DORMITORY B1;IZZATUL KARIMAH;EMPLOYEE BADGE;20432;EMPLOYEE;NDT ENGINEER;SR. STAFF - ENGINEER/ SPECIALIST;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
161;DM.B1.110;DORMITORY B1;NEW HIRE;;;;;;;;;;;;;;;;;;;;;;;
162;DM.B1.110;DORMITORY B1;ZAHRA FAUZI ALAWI;EMPLOYEE BADGE;20719;EMPLOYEE;IH & OH OFFICER;STAFF - OFFICER;HSE;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
163;DM.B1.111;DORMITORY B1;NAFRUDIN;EMPLOYEE BADGE;20422;EMPLOYEE;[B] SHIFT CALCINE TRANSFER SYSTEM (CTS) SUPERVISOR;STAFF - SUPERVISOR;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
164;DM.B1.111;DORMITORY B1;BASRI ADNAN SYAMSUDDIN;EMPLOYEE BADGE;20421;EMPLOYEE;[D] SHIFT REDUCTION KILN SUPERVISOR;STAFF - SUPERVISOR;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
165;DM.B1.112;DORMITORY B1;AGUS;EMPLOYEE BADGE;10190;EMPLOYEE;MECHANICAL ELECTRICAL TECHNICIAN;STAFF - SUPERVISOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
166;DM.B1.112;DORMITORY B1;DAHSAN;EMPLOYEE BADGE;20794;EMPLOYEE;FURNACE ELECTRIC SUPERVISOR;STAFF - SUPERVISOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
167;DM.B1.113;DORMITORY B1;AHMAD RIFAL FADLI;EMPLOYEE BADGE;20183;EMPLOYEE;AUTOMATION ENGINEER;STAFF - ENGINEER/ GEOLOGIST;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
168;DM.B1.113;DORMITORY B1;ARIA SAFFANA DARMAWAN;EMPLOYEE BADGE;20426;EMPLOYEE;FURNACE MECHANIC SUPERVISOR;STAFF - SUPERVISOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
169;DM.B1.114;DORMITORY B1;SARWAN;EMPLOYEE BADGE;20433;EMPLOYEE;[CMP] MECHANICAL ENGINEER;STAFF - ENGINEER/ GEOLOGIST;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
170;DM.B1.114;DORMITORY B1;ANDRE CHRISTAUVER;EMPLOYEE BADGE;20419;EMPLOYEE;[FS] PLANNER FABRICATION;STAFF - OFFICER;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
171;DM.A3.115;DORMITORY B1;SUHANDI;EMPLOYEE BADGE;20652;EMPLOYEE;[CMP] MECHANICAL ENGINEER;STAFF - ENGINEER/ GEOLOGIST;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
172;DM.A3.115;DORMITORY B1;MUHAMMAD GIKANO SABILLAH;EMPLOYEE BADGE;20604;EMPLOYEE;[CMP] INSTRUMENT ENGINEER;STAFF - ENGINEER/ GEOLOGIST;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
173;DM.B1.116;DORMITORY B1;ARIS ZARAZAK TAMBING;EMPLOYEE BADGE;20616;EMPLOYEE;MECHANICAL MAINTENANCE UTILITIES SUPERVISOR;STAFF - SUPERVISOR;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
174;DM.B1.116;DORMITORY B1;RAYHAN MAULANA PUTRA;EMPLOYEE BADGE;20796;EMPLOYEE;[RK] PROCESS ENGINEER SHIFT;STAFF - SUPERVISOR;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
175;DM.B1.117;DORMITORY B1;YUSUF SATTU;EMPLOYEE BADGE;20087;EMPLOYEE;INVENTORY PLANNING & CATALOGUING SUPERVISOR;STAFF - SUPERVISOR;SCM;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
176;DM.B1.117;DORMITORY B1;YOSAPAT KARO KARO;EMPLOYEE BADGE;20633;EMPLOYEE;[FS] PROCESS ENGINEER SHIFT;STAFF - ENGINEER/ GEOLOGIST;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
177;DM.B1.118;DORMITORY B1;HALIM AL MUSHAWWIR;EMPLOYEE BADGE;20620;EMPLOYEE;METAL ACCOUNTING SUPERINTENDENT;SR. STAFF - SUPERINTENDENT;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
178;DM.B1.118;DORMITORY B1;LEO CANDRA;EMPLOYEE BADGE;20623;EMPLOYEE;[B] SHIFT FURNACE SUPERVISOR;STAFF - SUPERVISOR;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
179;DM.B1.119;DORMITORY B1;MUSHOLIZAKY AFLAHAL MU'MIN;EMPLOYEE BADGE;20638;EMPLOYEE;METALLURGICAL ENGINEER;STAFF - ENGINEER/ GEOLOGIST;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
180;DM.B1.119;DORMITORY B1;VETSON GOODMAN LAWANDI;EMPLOYEE BADGE;20080;EMPLOYEE;DRAFTMAN MECHANICAL OR CIVIL;STAFF - OFFICER;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
181;DM.B1.120;DORMITORY B1;AHMAD KAPRAWI;EMPLOYEE BADGE;20656;EMPLOYEE;RECEIVING & BINNING SUPERVISOR;STAFF - SUPERVISOR;SCM;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
182;DM.B1.120;DORMITORY B1;IRFAN AFANDIE;EMPLOYEE BADGE;20651;EMPLOYEE;[CMP] MECHANICAL ENGINEER;STAFF - ENGINEER/ GEOLOGIST;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
183;DM.B1.201;DORMITORY B1;VISITOR 1;;;;;;;;;;;;;;;;;;;;;;;
184;DM.B1.201;DORMITORY B1;VACANT 1;;;;;;;;;;;;;;;;;;;;;;;
185;DM.B1.202;DORMITORY B1;ROMA FAISAL;EMPLOYEE BADGE;11608;EMPLOYEE;[CNI] CONSTRUCTION & MAINTENANCE SUPERINTENDENT;SR. STAFF - SUPERINTENDENT;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
186;DM.B1.202;DORMITORY B1;MUHAMMAD MACHDUM IBROHIM;EMPLOYEE BADGE;11610;EMPLOYEE;[CNI] CIVIL ENGINEER;STAFF - ENGINEER/ GEOLOGIST;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
187;DM.B1.203;DORMITORY B1;NABILLA MURNI HASANA;EMPLOYEE BADGE;20788;EMPLOYEE;[CMP] SITE SMELTER/CONSTRUCTION PAYROLL JUNIOR OFFICER;STAFF - OFFICER;HC;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
188;DM.B1.203;DORMITORY B1;NURUL FARADILLAH;EMPLOYEE BADGE;20397;EMPLOYEE;SECRETARY & DOCUMENT CONTROL;STAFF - OFFICER;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
189;DM.B1.204;DORMITORY B1;VISITOR 1;;;;;;;;;;;;;;;;;;;;;;;
190;DM.B1.204;DORMITORY B1;VISITOR 2;;;;;;;;;;;;;;;;;;;;;;;
191;DM.B1.205;DORMITORY B1;YACOBUS BUNTULOBO;EMPLOYEE BADGE;A1062;EMPLOYEE;MAINTENANCE ADVISOR;SR. STAFF;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
192;DM.B1.206;DORMITORY B1;ABEDNEDJU WOWILING;EMPLOYEE BADGE;20770;EMPLOYEE;EXPORT IMPORT SPECIALIST;SR. STAFF - ENGINEER/ SPECIALIST;;PT. CMP;SPECIAL GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
193;DM.B1.207;DORMITORY B1;VISITOR 1;;;;;;;;;;;;;;;;;;;;;;;
194;DM.B1.207;DORMITORY B1;VISITOR 2;;;;;;;;;;;;;;;;;;;;;;;
195;DM.B1.208;DORMITORY B1;IKA ALFIONITA LILING;EMPLOYEE BADGE;11539;EMPLOYEE;[CNI] PARAMEDIC;STAFF - OFFICER;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
196;DM.B1.208;DORMITORY B1;EGA ANGGISTA PUTRI;EMPLOYEE BADGE;20768;EMPLOYEE;SALES ADMINISTRATION & INVOICING OFFICER;STAFF - OFFICER;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
197;DM.B1.208;DORMITORY B1;VACANT 1;;;;;;;;;;;;;;;;;;;;;;;
198;DM.B1.209;DORMITORY B1;SUSAN SUGIANTI;EMPLOYEE BADGE;A1075;EMPLOYEE;CIVIL ENGINEER;STAFF - ENGINEER/ GEOLOGIST;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
199;DM.B1.209;DORMITORY B1;VACANT 1;;;;;;;;;;;;;;;;;;;;;;;
200;DM.B1.209;DORMITORY B1;VACANT 2;;;;;;;;;;;;;;;;;;;;;;;
201;DM.B1.210;DORMITORY B1;SOLANA MART 1;;;;;;;OWNER;SPECIAL GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
202;DM.B1.210;DORMITORY B1;SOLANA MART 2;;;;;;;OWNER;SPECIAL GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
203;DM.B1.211;DORMITORY B1;ALDILLAH;EMPLOYEE BADGE;20898;EMPLOYEE;[CMP] FACILITY BUILDING SUPERVISOR;STAFF - SUPERVISOR;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
204;DM.B1.211;DORMITORY B1;IBRAHIM ARIE SANTOSO;EMPLOYEE BADGE;20671;EMPLOYEE;EXIM SUPERVISOR;STAFF - SUPERVISOR;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
205;DM.B1.212;DORMITORY B1;LISTRA JESIKA PONGRATTE;EMPLOYEE BADGE;20769;EMPLOYEE;MANDARIN INTEPRETERS (SHIFT);STAFF - OFFICER;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
206;DM.B1.212;DORMITORY B1;VACANT 1;;;;;;;;;;;;;;;;;;;;;;;
207;DM.B1.212;DORMITORY B1;FATIKA DWIPUTRI PAYUNG;EMPLOYEE BADGE;20006;EMPLOYEE;[CMP] ADMIN PROJECT;STAFF - OFFICER;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
208;DM.B1.213;DORMITORY B1;PONCO DARMO JATI;EMPLOYEE BADGE;20683;EMPLOYEE;[SCM-WIM-SPV] WAREHOUSE RESOURCES SERVICES (WH-IM) SUPERVISOR;STAFF - SUPERVISOR;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
209;DM.B1.213;DORMITORY B1;RONAL BUNTULOBO;EMPLOYEE BADGE;20687;EMPLOYEE;WAREHOUSE COUNTER & DELIVERY SERVICES SUPERVISOR;STAFF - SUPERVISOR;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
210;DM.B1.214;DORMITORY B1;INNA ANNISA SAMPETODING;EMPLOYEE BADGE;11519;EMPLOYEE;SYSTEM AND COMPLIANCE OFFICER;STAFF - OFFICER;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
211;DM.B1.214;DORMITORY B1;JASMINE RIZKIMUKTI;EMPLOYEE BADGE;11499;EMPLOYEE;JUNIOR CIVIL ENGINEER;STAFF - ENGINEER/ GEOLOGIST;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
212;DM.B1.214;DORMITORY B1;ERI RUSMIATI;EMPLOYEE BADGE;20742;EMPLOYEE;MANDARIN INTEPRETERS (SHIFT);STAFF - OFFICER;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
213;DM.B1.215;DORMITORY B1;HERI YULIANUS TIA;EMPLOYEE BADGE;20807;EMPLOYEE;SMELTER OPERATION DOCTOR;STAFF - SUPERVISOR;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
214;DM.B1.215;DORMITORY B1;LA ODE NIZAM ASRIM;EMPLOYEE BADGE;20795;EMPLOYEE;[DT] PROCESS ENGINEER SHIFT;STAFF - ENGINEER/ GEOLOGIST;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
215;DM.B1.216;DORMITORY B1;VISITOR 1;;;;;;;;;;;;;;;;;;;;;;;
216;DM.B1.217;DORMITORY B1;VISITOR 1;;;;;;;;;;;;;;;;;;;;;;;
217;DM.B1.218;DORMITORY B1;VISITOR 1;;;;;;;;;;;;;;;;;;;;;;;
218;DM.B1.219;DORMITORY B1;A. YANI ESBE;EMPLOYEE BADGE;11280;EMPLOYEE;OCCUPATIONAL HEALTH & SAFETY MANAGER;SR. STAFF - MANAGER;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
219;DM.B1.220;DORMITORY B1;ERLIN HARRY;EMPLOYEE BADGE;11522;EMPLOYEE;NURSERY SUPERINTENDENT;SR. STAFF - SUPERINTENDENT;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;SATELIT CANTEEN;SATELIT CANTEEN;SATELIT CANTEEN;;;;;;;;;;;
220;DM.R1.101;DORMITORY R1;YUSAN SUTOPO;EMPLOYEE BADGE;20378;EMPLOYEE;[C] OPERATOR CONTROL ROOM REDUCTION KILN;STAFF - OFFICER;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
221;DM.R1.101;DORMITORY R1;SYAMSUL BACHRI;EMPLOYEE BADGE;20380;EMPLOYEE;[C] CONTROL ROOM OPERATOR;STAFF - OFFICER;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
222;DM.R1.102;DORMITORY R1;DAUD MARENDEN;EMPLOYEE BADGE;20167;EMPLOYEE;[B] OPERATOR CONTROL ROOM DRYER;STAFF - OFFICER;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
223;DM.R1.102;DORMITORY R1;YULIO JOHAN PALALLO;EMPLOYEE BADGE;20640;EMPLOYEE;MANDARIN INTEPRETERS (SHIFT);STAFF - OFFICER;HC;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
224;DM.R1.103;DORMITORY R1;HANDAYANI;EMPLOYEE BADGE;20692;EMPLOYEE;WAREHOUSE COUNTER & DELIVERY SERVICES LEADHAND;STAFF - OFFICER;SCM;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
225;DM.R1.103;DORMITORY R1;RIAN RAMADHAN N. YAHMAN,SE;EMPLOYEE BADGE;20725;EMPLOYEE;[WIM] STOREMAN;STAFF - OFFICER;SCM;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
226;DM.R1.104;DORMITORY R1;IRFAN HAYATUDIN;EMPLOYEE BADGE;20268;EMPLOYEE;[A] OPERATOR CONTROL ROOM COAL MILL;STAFF - OFFICER;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
227;DM.R1.104;DORMITORY R1;AHMAT HARIYONO;EMPLOYEE BADGE;20347;EMPLOYEE;[C] OPERATOR CONTROL ROOM COAL MILL;STAFF - OFFICER;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
228;DM.R1.105;DORMITORY R1;RICKYANTO DODE';EMPLOYEE BADGE;20782;EMPLOYEE;[WIM] STOREMAN;STAFF - OFFICER;SCM;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
229;DM.R1.105;DORMITORY R1;MUH. ANUGRAH JUFRI;EMPLOYEE BADGE;20809;EMPLOYEE;INVENTORY CONTROL;STAFF - OFFICER;SCM;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
230;DM.R1.106;DORMITORY R1;DAUD TONGLOLANGI;EMPLOYEE BADGE;20195;EMPLOYEE;[A] OPERATOR CONTROL ROOM CALCINE TRANSFER SYSTEM;STAFF - OFFICER;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
231;DM.R1.106;DORMITORY R1;LAZARUS BARA PARAPASAN;EMPLOYEE BADGE;20169;EMPLOYEE;[A] CONTROL ROOM OPERATOR;STAFF - OFFICER;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
232;DM.R1.107;DORMITORY R1;HAFIF IKROM MAULANA;EMPLOYEE BADGE;20776;EMPLOYEE;MANDARIN INTEPRETERS (SHIFT);STAFF - OFFICER;HC;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
233;DM.R1.107;DORMITORY R1;IBRAHIM ABD. AZIS;EMPLOYEE BADGE;20274;EMPLOYEE;[DKM] PLANNER MECHANICAL;STAFF - OFFICER;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
234;DM.R1.108;DORMITORY R1;HARTONO ALSAD;EMPLOYEE BADGE;20279;EMPLOYEE;[A] OPERATOR CONTROL ROOM REDUCTION KILN;STAFF - OFFICER;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
235;DM.R1.108;DORMITORY R1;AMAT SUBANDY;EMPLOYEE BADGE;20350;EMPLOYEE;[B] OPERATOR CONTROL ROOM REDUCTION KILN;STAFF - OFFICER;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
236;DM.R1.109;DORMITORY R1;ARMIN NUR;EMPLOYEE BADGE;20471;EMPLOYEE;ANALYST INSTRUMENT;STAFF - OFFICER;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
237;DM.R1.109;DORMITORY R1;NAIM NASSA;EMPLOYEE BADGE;20476;EMPLOYEE;[C] OPERATOR CONTROL ROOM CALCINE TRANSFER SYSTEM;STAFF - OFFICER;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
238;DM.R1.110;DORMITORY R1;BENI MONTOLALU;EMPLOYEE BADGE;20194;EMPLOYEE;[B] CONTROL ROOM OPERATOR;STAFF - OFFICER;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
239;DM.R1.110;DORMITORY R1;A BEE, KHOE;EMPLOYEE BADGE;20694;EMPLOYEE;MANDARIN INTEPRETERS (SHIFT);STAFF - OFFICER;HC;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
240;DM.R1.111;DORMITORY R1;REZA YUDHISTIRA;EMPLOYEE BADGE;20416;EMPLOYEE;[D] OPERATOR CONTROL ROOM COAL MILL;STAFF - OFFICER;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
241;DM.R1.111;DORMITORY R1;AGUSTINUS MONCUBE;EMPLOYEE BADGE;20420;EMPLOYEE;[D] OPERATOR CONTROL ROOM CALCINE TRANSFER SYSTEM;STAFF - OFFICER;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
242;DM.R1.112;DORMITORY R1;ENDANG ROHENDI;EMPLOYEE BADGE;20193;EMPLOYEE;[B] OPERATOR CONTROL ROOM COAL MILL;STAFF - OFFICER;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
243;DM.R1.112;DORMITORY R1;AHMAD JEJE;EMPLOYEE BADGE;20168;EMPLOYEE;[A] OPERATOR CONTROL ROOM DRYER;STAFF - OFFICER;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
244;DM.R1.113;DORMITORY R1;ARAFAH;EMPLOYEE BADGE;20395;EMPLOYEE;[D] CONTROL ROOM OPERATOR;STAFF - OFFICER;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
245;DM.R1.113;DORMITORY R1;SULKIFLY TALLESANG;EMPLOYEE BADGE;20815;EMPLOYEE;[DKM] PLANNER MECHANICAL;STAFF - OFFICER;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
246;DM.R1.114;DORMITORY R1;HAERUDDIN;EMPLOYEE BADGE;11103;EMPLOYEE;FOREMAN STOCKYARD & BARGING;STAFF - OFFICER;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
247;DM.R1.114;DORMITORY R1;INDRA KUSUMA;EMPLOYEE BADGE;20427;EMPLOYEE;[B] SHIFT DRYER SUPERVISOR;STAFF - OFFICER;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
248;DM.R1.115;DORMITORY R1;ANTHON TANDI ARRUAN;EMPLOYEE BADGE;20074;EMPLOYEE;FURNACE STEADY DAY SUPERVISOR;STAFF - SUPERVISOR;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
249;DM.R1.115;DORMITORY R1;SYAMSUL QAMAR;EMPLOYEE BADGE;20093;EMPLOYEE;INSTRUCTOR MODUL NIKEL MATTE;STAFF - OFFICER;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
250;DM.R1.116;DORMITORY R1;THOMAS;EMPLOYEE BADGE;20073;EMPLOYEE;LF & SHOTTING STEADY DAY SUPERVISOR;STAFF - SUPERVISOR;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
251;DM.R1.116;DORMITORY R1;HARI PRASETYO;EMPLOYEE BADGE;20473;EMPLOYEE;INSTRUCTOR UTILITIES;STAFF - OFFICER;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
252;DM.R1.117;DORMITORY R1;LOIS VERNANDY;EMPLOYEE BADGE;20639;EMPLOYEE;SAFETY OFFICER;STAFF - OFFICER;HSE;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
253;DM.R1.117;DORMITORY R1;ANDI MUHAMMAD BASRI;EMPLOYEE BADGE;20724;EMPLOYEE;[CMP] PARAMEDIC;STAFF - OFFICER;HSE;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
254;DM.R1.118;DORMITORY R1;VACANT 1;;;;;;;;;;;;;;;;;;;;;;;
255;DM.R1.118;DORMITORY R1;VACANT 2;;;;;;;;;;;;;;;;;;;;;;;
256;DM.R1.119;DORMITORY R1;BURHANUDDIN;EMPLOYEE BADGE;20693;EMPLOYEE;NDT TECHNICIAN;STAFF - OFFICER;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
257;DM.R1.119;DORMITORY R1;IRWAN;EMPLOYEE BADGE;11246;EMPLOYEE;MINING CREW & CHECKER;STAFF - OFFICER;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
258;DM.R1.120;DORMITORY R1;IMANUEL RISA;EMPLOYEE BADGE;20660;EMPLOYEE;INVENTORY CONTROL;STAFF - OFFICER;SCM;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
259;DM.R1.120;DORMITORY R1;REGI GALINGGANG;EMPLOYEE BADGE;20684;EMPLOYEE;WAREHOUSE BINNING LEADHAND;STAFF - OFFICER;SCM;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
260;DM.R1.201;DORMITORY R1;SABRI;EMPLOYEE BADGE;10810;EMPLOYEE;COOK;STAFF - OFFICER;SITE GENERAL AFFAIR;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
261;DM.R1.201;DORMITORY R1;VACANT 1;;;;;;;;;;;;;;;;;;;;;;;
262;DM.R1.202;DORMITORY R1;MUHAMMAD RIDWAN;EMPLOYEE BADGE;10623;EMPLOYEE;COOK;STAFF - OFFICER;SITE GENERAL AFFAIR;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
263;DM.R1.202;DORMITORY R1;SINGGIT;EMPLOYEE BADGE;10695;EMPLOYEE;[CNI] COOK HELPER;STAFF - OFFICER;SITE GENERAL AFFAIR;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
264;DM.R1.203;DORMITORY R1;MUH. HAIDIR TANDEAN;EMPLOYEE BADGE;20686;EMPLOYEE;CONTAINER & BREAKBULK HANDLING LEADHAND;STAFF - OFFICER;SCM;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
265;DM.R1.203;DORMITORY R1;INDRA ALFADRIN PATOLA;EMPLOYEE BADGE;20691;EMPLOYEE;AUXILIARY MATERIAL HANDLING LEADHAND;STAFF - OFFICER;SCM;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
266;DM.R1.204;DORMITORY R1;JUNIAMIN DJAMAL;EMPLOYEE BADGE;11143;EMPLOYEE;SENIOR COOK;STAFF - OFFICER;SITE GENERAL AFFAIR;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
267;DM.R1.204;DORMITORY R1;YAPRIANUS MASUA;EMPLOYEE BADGE;10392;EMPLOYEE;COOK;STAFF - OFFICER;SITE GENERAL AFFAIR;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
268;DM.R1.205;DORMITORY R1;DEWO ARMANDO;;;;IT SUPPORT;STAFF - OFFICER;IT;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
269;DM.R1.205;DORMITORY R1;JONISWAN;EMPLOYEE BADGE;11364;EMPLOYEE;JUNIOR NETWORK ENGINEER;STAFF - ENGINEER/ GEOLOGIST;IT;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
270;DM.R1.206;DORMITORY R1;AKHMAD MUBARAK;EMPLOYEE BADGE;20609;EMPLOYEE;RESCUE SUPERVISOR;STAFF - SUPERVISOR;HSE;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
271;DM.R1.206;DORMITORY R1;ACEP ALLO GAWEN;EMPLOYEE BADGE;20613;EMPLOYEE;WAREHOUSE ALL AROUND SERVICES LEADHAND;STAFF - OFFICER;SCM;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
272;DM.R1.207;DORMITORY R1;TABRY RANGGINA MATASIK;EMPLOYEE BADGE;20621;EMPLOYEE;WAREHOUSE RECEIVING LEADHAND;STAFF - OFFICER;SCM;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
273;DM.R1.207;DORMITORY R1;ANTONO;EMPLOYEE BADGE;20636;EMPLOYEE;INVENTORY CONTROL;STAFF - OFFICER;SCM;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
274;DM.R1.208;DORMITORY R1;JANUARIUS DASILVA PEDON;EMPLOYEE BADGE;20655;EMPLOYEE;WAREHOUSE RESOURCE SERVICE LEADHAND;STAFF - OFFICER;SCM;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
275;DM.R1.208;DORMITORY R1;EKI DWIYANTORO SAPUTRA;EMPLOYEE BADGE;20697;EMPLOYEE;[CMP] PARAMEDIC;STAFF - OFFICER;EMU;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
276;DM.R1.209;DORMITORY R1;YEHEZKIEL RICKY;EMPLOYEE BADGE;20412;EMPLOYEE;GENERAL SUPPORT;STAFF - OFFICER;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
277;DM.R1.209;DORMITORY R1;ARISALDI;EMPLOYEE BADGE;20662;EMPLOYEE;SAFETY OFFICER PROJECT;STAFF - OFFICER;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
278;DM.R1.210;DORMITORY R1;MUH. SOFYAN;EMPLOYEE BADGE;20431;EMPLOYEE;[D] CONTROL ROOM OPERATOR UTILITIES;STAFF - OFFICER;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
279;DM.R1.210;DORMITORY R1;MUHAMMAD RIDWAN FAISAL;EMPLOYEE BADGE;20411;EMPLOYEE;[C] CONTROL ROOM OPERATOR UTILITIES;STAFF - OFFICER;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
280;DM.R1.211;DORMITORY R1;JONATHAN ROMEO SITUMORANG;EMPLOYEE BADGE;20730;EMPLOYEE;[CMP] PARAMEDIC;STAFF - OFFICER;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
281;DM.R1.211;DORMITORY R1;AZMIE NAUFAL AKMAL;EMPLOYEE BADGE;20731;EMPLOYEE;ENVIRONMENT OFFICER;STAFF - OFFICER;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
282;DM.R1.212;DORMITORY R1;FARHAN RAMADHAN;EMPLOYEE BADGE;20142;EMPLOYEE;[A] CONTROL ROOM OPERATOR UTILITIES;STAFF - OFFICER;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
283;DM.R1.212;DORMITORY R1;MUH YASWAN RAMADANA YUSFA;EMPLOYEE BADGE;20159;EMPLOYEE;[B] CONTROL ROOM OPERATOR UTILITIES;STAFF - OFFICER;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
284;DM.R1.213;DORMITORY R1;MIRZA SALEH KHAN;EMPLOYEE BADGE;20829;EMPLOYEE;TRAINING & CERTIFICATION OFFICER;STAFF - OFFICER;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
285;DM.R1.213;DORMITORY R1;ANGGA WIDYA NIRMAN;EMPLOYEE BADGE;20739;EMPLOYEE;TECHNOLOGYST METROLOGY;STAFF - OFFICER;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
286;DM.R1.214;DORMITORY R1;YOSEP RISAL ;EMPLOYEE BADGE;20734;EMPLOYEE;TRAINING & CERTIFICATION OFFICER;STAFF - OFFICER;HSE;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
287;DM.R1.214;DORMITORY R1;RICHARD PASARIBU;EMPLOYEE BADGE;20711;EMPLOYEE;[CMP] PARAMEDIC;STAFF - OFFICER;HSE;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
288;DM.R1.215;DORMITORY R1;ANDY;EMPLOYEE BADGE;20741;EMPLOYEE;MANDARIN INTEPRETERS (SHIFT);STAFF - OFFICER;HC;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
289;DM.R1.215;DORMITORY R1;ESRA RATTU LEME;EMPLOYEE BADGE;20738;EMPLOYEE;MANDARIN INTEPRETERS (SHIFT);STAFF - OFFICER;HC;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
290;DM.R1.216;DORMITORY R1;MAMAN SULAEMAN;EMPLOYEE BADGE;11477;EMPLOYEE;CHEF COOK & FOOD QUALITY COORDINATOR & TEAM;STAFF - OFFICER;HC;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
291;DM.R1.216;DORMITORY R1;YULIANUS MAESAK;EMPLOYEE BADGE;11424;EMPLOYEE;IT SUPPORT;STAFF - OFFICER;IT;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
292;DM.R1.217;DORMITORY R1;HERDIANTO;EMPLOYEE BADGE;20752;EMPLOYEE;[WIM] STOREMAN;STAFF - OFFICER;SCM;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
293;DM.R1.217;DORMITORY R1;IRIYANTO LAWA PALIMBUNGA;EMPLOYEE BADGE;20750;EMPLOYEE;[SCM-INV-CAT] CATALOGER;STAFF - OFFICER;SCM;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
294;DM.R1.218;DORMITORY R1;JIMMY;EMPLOYEE BADGE;20753;EMPLOYEE;MANDARIN INTEPRETERS (SHIFT);STAFF - OFFICER;HC;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
295;DM.R1.218;DORMITORY R1;JIMMY DIETER BUDIMAN SIBALA;EMPLOYEE BADGE;20759;EMPLOYEE;TRAFFIC & HUB HANDLING LEADHAND;STAFF - OFFICER;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
296;DM.R1.219;DORMITORY R1;BOBY;EMPLOYEE BADGE;20765;EMPLOYEE;MANDARIN INTEPRETERS (SHIFT);STAFF - OFFICER;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
297;DM.R1.219;DORMITORY R1;RIVALDI RANGGINA MATIPA;EMPLOYEE BADGE;20764;EMPLOYEE;[WIM] STOREMAN;STAFF - OFFICER;SCM;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
298;DM.R1.220;DORMITORY R1;NASRUDDIN;EMPLOYEE BADGE;A1049;EMPLOYEE;PROFESSIONAL ASSIGNMENT (PA);STAFF - OFFICER;HC;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
299;DM.R1.220;DORMITORY R1;ANDI MAULANA MALIK IBRAHIM;EMPLOYEE BADGE;20756;EMPLOYEE;MANDARIN INTEPRETERS (SHIFT);STAFF - OFFICER;HC;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
300;DM.R2.101;DORMITORY R2;APD SCM;;;;;;;;;;;;;;;;;;;;;;;
301;DM.R2.101;DORMITORY R2;APD SCM;;;;;;;;;;;;;;;;;;;;;;;
302;DM.R2.101;DORMITORY R2;APD SCM;;;;;;;;;;;;;;;;;;;;;;;
303;DM.R2.102;DORMITORY R2;ARNOS;EMPLOYEE BADGE;11556;EMPLOYEE;[CNI] PARAMEDIC;STAFF;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
304;DM.R2.102;DORMITORY R2;BAYU PRASETYO;EMPLOYEE BADGE;11540;EMPLOYEE;[CNI] PARAMEDIC;STAFF;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
305;DM.R2.102;DORMITORY R2;VACANT 1;;;;;;;;;;;;;;;;;;;;;;;
306;DM.R2.102;DORMITORY R2;VACANT 2;;;;;;;;;;;;;;;;;;;;;;;
307;DM.R2.103;DORMITORY R2;APD SCM;;;;;;;;;;;;;;;;;;;;;;;
308;DM.R2.103;DORMITORY R2;APD SCM;;;;;;;;;;;;;;;;;;;;;;;
309;DM.R2.103;DORMITORY R2;APD SCM;;;;;;;;;;;;;;;;;;;;;;;
310;DM.R2.104;DORMITORY R2;VACANT 1;;;;;;;;;;;;;;;;;;;;;;;
311;DM.R2.104;DORMITORY R2;SUHARMAN;EMPLOYEE BADGE;11571;EMPLOYEE;GRADE CONTROL FOREMAN;NON STAFF;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
312;DM.R2.104;DORMITORY R2;REYMON;EMPLOYEE BADGE;11561;EMPLOYEE;GRADE CONTROL FOREMAN;NON STAFF;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
313;DM.R2.104;DORMITORY R2;ZULFIQRI;EMPLOYEE BADGE;11559;EMPLOYEE;GRADE CONTROL FOREMAN;NON STAFF;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
314;DM.R2.105;DORMITORY R2;VACANT 1;;;;;;;;;;;;;;;;;;;;;;;
315;DM.R2.105;DORMITORY R2;HASRIADI;EMPLOYEE BADGE;20818;EMPLOYEE;[D] OPERATOR SKIMMING FURNACE;NON STAFF - OPERATOR;PP;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
316;DM.R2.105;DORMITORY R2;VACANT 2;;;;;;;;;;;;;;;;;;;;;;;
317;DM.R2.105;DORMITORY R2;VACANT 3;;;;;;;;;;;;;;;;;;;;;;;
318;DM.R2.106;DORMITORY R2;RAHMAN RIPALDI;EMPLOYEE BADGE;20444;EMPLOYEE;FIRE CREW;NON STAFF;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
319;DM.R2.106;DORMITORY R2;EKI DWIYANTORO SAPUTRA;EMPLOYEE BADGE;20697;EMPLOYEE;[CMP] PARAMEDIC;STAFF;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
320;DM.R2.106;DORMITORY R2;AL ZIYARIS ABRIAN KADIRUN;EMPLOYEE BADGE;20442;EMPLOYEE;FIRE CREW;NON STAFF;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
321;DM.R2.107;DORMITORY R2;ROKKY DERMAWAN;EMPLOYEE BADGE;20440;EMPLOYEE;FIRE CREW;NON STAFF;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
322;DM.R2.107;DORMITORY R2;SUDARWAN;EMPLOYEE BADGE;20443;EMPLOYEE;FIRE CREW;NON STAFF;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
323;DM.R2.107;DORMITORY R2;EDWIN KRISTIAN SALMON;EMPLOYEE BADGE;20438;EMPLOYEE;FIRE CREW;NON STAFF;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
324;DM.R2.108;DORMITORY R2;VISITOR (IT);;;;;;;;;;;;;;;;;;;;;;;
325;DM.R2.108;DORMITORY R2;VACANT 1;;;;;;;;;;;;;;;;;;;;;;;
326;DM.R2.108;DORMITORY R2;VACANT 2;;;;;;;;;;;;;;;;;;;;;;;
327;DM.R2.109;DORMITORY R2;VACANT 1;;;;;;;;;;;;;;;;;;;;;;;
328;DM.R2.109;DORMITORY R2;VACANT 2;;;;;;;;;;;;;;;;;;;;;;;
329;DM.R2.109;DORMITORY R2;VACANT 3;;;;;;;;;;;;;;;;;;;;;;;
330;DM.R2.110;DORMITORY R2;FARHAN ;;;;;;;;;;;;;;;;;;;;;;;
331;DM.R2.110;DORMITORY R2;MUHAMMAD IKSAN;;;;;;;;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
332;DM.R2.110;DORMITORY R2;REY;;;;;;;;;;;;;;;;;;;;;;;
333;DM.R2.111;DORMITORY R2;VACANT 1;;;;;;;;;;;;;;;;;;;;;;;
334;DM.R2.111;DORMITORY R2;VACANT 2;;;;;;;;;;;;;;;;;;;;;;;
335;DM.R2.111;DORMITORY R2;VACANT 3;;;;;;;;;;;;;;;;;;;;;;;
336;DM.R2.112;DORMITORY R2;VACANT 1;;;;;;;;;;;;;;;;;;;;;;;
337;DM.R2.112;DORMITORY R2;VACANT 2;;;;;;;;;;;;;;;;;;;;;;;
338;DM.R2.112;DORMITORY R2;VACANT 3;;;;;;;;;;;;;;;;;;;;;;;
339;DM.R2.113;DORMITORY R2;BRIMOB 4;;;;;;;;;;;;;;;;;;;;;;;
340;DM.R2.113;DORMITORY R2;BRIMOB 5;;;;;;;;;;;;;;;;;;;;;;;
341;DM.R2.113;DORMITORY R2;BRIMOB 6;;;;;;;;;;;;;;;;;;;;;;;
342;DM.R2.114;DORMITORY R2;VACANT 1;;;;;;;;;;;;;;;;;;;;;;;
343;DM.R2.114;DORMITORY R2;VACANT 2;;;;;;;;;;;;;;;;;;;;;;;
344;DM.R2.114;DORMITORY R2;VACANT 3;;;;;;;;;;;;;;;;;;;;;;;
345;DM.R2.115;DORMITORY R2;BRIMOB 7;;;;;;;;;;;;;;;;;;;;;;;
346;DM.R2.115;DORMITORY R2;BRIMOB 8;;;;;;;;;;;;;;;;;;;;;;;
347;DM.R2.115;DORMITORY R2;BRIMOB 9;;;;;;;;;;;;;;;;;;;;;;;
348;DM.R2.116;DORMITORY R2;VACANT 1;;;;;;;;;;;;;;;;;;;;;;;
349;DM.R2.116;DORMITORY R2;BRIMOB 10;;;;;;;;;;;;;;;;;;;;;;;
350;DM.R2.116;DORMITORY R2;VACANT 2;;;;;;;;;;;;;;;;;;;;;;;
351;DM.R2.117;DORMITORY R2;POLISI AIR 1;;;;;;;;;;;;;;;;;;;;;;;
352;DM.R2.117;DORMITORY R2;POLISI AIR 2;;;;;;;;;;;;;;;;;;;;;;;
353;DM.R2.117;DORMITORY R2;VACANT 1;;;;;;;;;;;;;;;;;;;;;;;
354;DM.R2.118;DORMITORY R2;VACANT 1;;;;;;;;;;;;;;;;;;;;;;;
355;DM.R2.118;DORMITORY R2;VACANT 2;;;;;;;;;;;;;;;;;;;;;;;
356;DM.R2.118;DORMITORY R2;VACANT 3;;;;;;;;;;;;;;;;;;;;;;;
357;DM.R2.119;DORMITORY R2;MUHAMMAD HASRULLAH;EMPLOYEE BADGE;20813;EMPLOYEE;[C] SHIFT ELECTRIC;NON STAFF;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
358;DM.R2.119;DORMITORY R2;MUSLIMIN MISA;EMPLOYEE BADGE;20814;EMPLOYEE;[C] SHIFT INSTRUMENT;NON STAFF;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
359;DM.R2.119;DORMITORY R2;LA NTAWU;EMPLOYEE BADGE;20834;EMPLOYEE;DRYER KILN INSTRUMENT;NON STAFF;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
360;DM.R2.120;DORMITORY R2;GUDANG GFS;;;;;;;;;;;;;;;;;;;;;;;
361;DM.R2.120;DORMITORY R2;GUDANG GFS;;;;;;;;;;;;;;;;;;;;;;;
362;DM.R2.120;DORMITORY R2;GUDANG GFS;;;;;;;;;;;;;;;;;;;;;;;
363;DM.R2.201;DORMITORY R2;JONI DEMMA'DIKA;EMPLOYEE BADGE;11628;EMPLOYEE;SECURITY INTELLIGENCE SUPERVISOR;STAFF - SUPERVISOR;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
364;DM.R2.201;DORMITORY R2;ANDI GESKHI RIZAL PANGERANG;EMPLOYEE BADGE;20842;EMPLOYEE;NICKEL PRODUCT MANAGEMENT HANDLING LEADHAND;STAFF - OFFICER;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
365;DM.R2.201;DORMITORY R2;VACANT 1;;;;;;;;;;;;;;;;;;;;;;;
366;DM.R2.202;DORMITORY R2;DANIEL BONTING;EMPLOYEE BADGE;11568;EMPLOYEE;MINE PRODUCTION SUPERVISOR;STAFF - SUPERVISOR;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
367;DM.R2.202;DORMITORY R2;VACANT 1;;;;;;;;;;;;;;;;;;;;;;;
368;DM.R2.202;DORMITORY R2;MAHYUDDIN;EMPLOYEE BADGE;11583;EMPLOYEE;MINE PRODUCTION SUPERVISOR;STAFF - SUPERVISOR;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
369;DM.R2.203;DORMITORY R2;MUH. AKBAR RIANTO;EMPLOYEE BADGE;20837;EMPLOYEE;[B] OPERATOR CALCINE CRANE;NON STAFF - OPERATOR;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
370;DM.R2.203;DORMITORY R2;SAFRIL SADRI;;;;OPERATOR CALCINE CRANE;NON STAFF - OPERATOR;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
371;DM.R2.203;DORMITORY R2;YAYAN ARHAM SAFRUDDIN;EMPLOYEE BADGE;20835;EMPLOYEE;[A] LADLE FURNACE OPERATOR;NON STAFF - OPERATOR;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
372;DM.R2.204;DORMITORY R2;MUHAMMAD DIAN APRIANSYAH;EMPLOYEE BADGE;11584;EMPLOYEE;CONTROL ROOM DISPATCH;STAFF - OFFICER;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
373;DM.R2.204;DORMITORY R2;MUH. AKHYAR A;EMPLOYEE BADGE;11586;EMPLOYEE;CONTROL ROOM DISPATCH;STAFF - OFFICER;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
374;DM.R2.204;DORMITORY R2;ABD GAFFAR;EMPLOYEE BADGE;11496;EMPLOYEE;CONTROL ROOM DISPATCH;STAFF - OFFICER;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
375;DM.R2.205;DORMITORY R2;ANDRI MUSHAR;EMPLOYEE BADGE;20836;EMPLOYEE;[C] OPERATOR HOT METAL CRANE;NON STAFF - OPERATOR;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
376;DM.R2.205;DORMITORY R2;UZUL RAHMAN YUS;EMPLOYEE BADGE;20840;EMPLOYEE;FURNACE INSTRUMENT;NON STAFF;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
377;DM.R2.205;DORMITORY R2;KHAEIRUL KADRI;EMPLOYEE BADGE;20812;EMPLOYEE;[C] OPERATOR SKIMMING FURNACE;NON STAFF - OPERATOR;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
378;DM.R2.206;DORMITORY R2;SOLANA MART;;;;;;;;;;;;;;;;;;;;;;;
379;DM.R2.206;DORMITORY R2;SOLANA MART;;;;;;;;;;;;;;;;;;;;;;;
380;DM.R2.206;DORMITORY R2;SOLANA MART;;;;;;;;;;;;;;;;;;;;;;;
381;DM.R2.207;DORMITORY R2;VACANT 1;;;;;;;;;;;;;;;;;;;;;;;
382;DM.R2.207;DORMITORY R2;ANDI OGENG ALAMSYAH;EMPLOYEE BADGE;11570;EMPLOYEE;[B] MINE OPERATION SUPERINTENDENT;SR. STAFF - SUPERINTENDENT;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
383;DM.R2.207;DORMITORY R2;VACANT 1;;;;;;;;;;;;;;;;;;;;;;;
384;DM.R2.208;DORMITORY R2;ADI DARADI;EMPLOYEE BADGE;11558;EMPLOYEE;DOKTER;STAFF - SUPERVISOR;;PT. CMP;REGULAR GUEST;STANDARD BUFFET;CENTRAL CANTEEN;CENTRAL CANTEEN;CENTRAL CANTEEN;;;;;;;;;;;
385;DM.R2.208;DORMITORY R2;VACANT 1;;;;;;;;;;;;;;;;;;;;;;;
386;DM.R2.209;DORMITORY R2;VACANT 1;;;;;;;;;;;;;;;;;;;;;;;
387;DM.R2.209;DORMITORY R2;VACANT 2;;;;;;;;;;;;;;;;;;;;;;;
388;DM.R2.209;DORMITORY R2;VACANT 3;;;;;;;;;;;;;;;;;;;;;;;
389;DM.R2.210;DORMITORY R2;VACANT 1;;;;;;;;;;;;;;;;;;;;;;;
390;DM.R2.210;DORMITORY R2;VACANT 2;;;;;;;;;;;;;;;;;;;;;;;
391;DM.R2.210;DORMITORY R2;VACANT 3;;;;;;;;;;;;;;;;;;;;;;;
392;DM.R2.211;DORMITORY R2;SAFETY SUPERVISOR;;;;;;;;;;;;;;;;;;;;;;;
393;DM.R2.211;DORMITORY R2;SAFETY DATA ANALYST SUPERVISOR;;;;;;;;;;;;;;;;;;;;;;;
394;DM.R2.211;DORMITORY R2;ACCOUNTING SUPERVISOR;;;;;;;;;;;;;;;;;;;;;;;
395;DM.R2.212;DORMITORY R2;VACANT 1;;;;;;;;;;;;;;;;;;;;;;;
396;DM.R2.212;DORMITORY R2;VACANT 2;;;;;;;;;;;;;;;;;;;;;;;
397;DM.R2.212;DORMITORY R2;VACANT 3;;;;;;;;;;;;;;;;;;;;;;;
398;DM.R2.213;DORMITORY R2;VACANT 1;;;;;;;;;;;;;;;;;;;;;;;
399;DM.R2.213;DORMITORY R2;VACANT 2;;;;;;;;;;;;;;;;;;;;;;;
400;DM.R2.213;DORMITORY R2;VACANT 3;;;;;;;;;;;;;;;;;;;;;;;
EOD;

$host = '127.0.0.1';
$db   = 'gfs_akomodasi';
$user = 'root';
$pass = '';

try {
     $pdo = new PDO("mysql:host=$host;dbname=$db;charset=utf8mb4", $user, $pass);
     $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

     $rooms = $pdo->query("SELECT id, room_no FROM rooms")->fetchAll(PDO::FETCH_ASSOC);
     $room_map = [];
     foreach ($rooms as $r) {
         $room_map[$r['room_no']] = $r['id'];
     }

     $lines = explode("\n", trim($csvData));
     $stmt = $pdo->prepare("INSERT INTO guests (room_id, name, personal_identification, reg_id_card, job, position, level_category, department, institution_company, occupants_category, meals_packages, breakfast_dp, lunch_dp, dinner_dp, registered_by, last_registration, remarks) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, NOW(), '')");

     $count = 0;
     foreach ($lines as $line) {
         $line = trim($line);
         if (empty($line) || str_starts_with($line, 'NO;') || str_starts_with($line, ';')) continue;
         
         $cols = explode(";", $line);
         if (count($cols) < 16) continue;

         $room_no = trim($cols[1]);
         if ($room_no === 'DM.A3.115' && strpos($line, 'DORMITORY B1') !== false) {
             $room_no = 'DM.B1.115';
         }
         if (!isset($room_map[$room_no])) {
             continue; // Skip if room doesn't exist
         }

         $stmt->execute([
             $room_map[$room_no],
             trim($cols[3]), // name
             trim($cols[4]), // personal_identification
             trim($cols[5]), // reg_id_card
             trim($cols[6]), // job
             trim($cols[7]), // position
             trim($cols[8]), // level_category
             trim($cols[9]), // department
             trim($cols[10]), // institution_company
             trim($cols[11]), // occupants_category
             trim($cols[12]), // meals_packages
             trim($cols[13]), // breakfast_dp
             trim($cols[14]), // lunch_dp
             trim($cols[15]), // dinner_dp
             'Admin' // registered_by
         ]);
         $count++;
     }
     
     echo "Successfully inserted $count records into the guests table.\n";
     
} catch (\PDOException $e) {
     echo "Error: " . $e->getMessage() . "\n";
}
